// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 4.2.2 by TAF Team.
// Generated from `./NewsServer.jce'
// **********************************************************************
var TradeDate = require("@up/trade-date");
TradeDate.init();
let data = require('../lib/data');
var News = require('./NewsServer.js').News;
module.exports.News = News;
var logger = require('../lib/log');
var moment = require('moment');
var Q = require('q');
var common = require('../lib/common');
var Taf = require("@taf/taf-rpc").Communicator.New();
Taf.setProperty('timeout',5000);
var util   = require('../lib/util');
var config = util.getConf();

var Common_HQSys = require("./CommonJce.js").HQSys;
var BasicData_HQSys = require("./BasicDataJce.js").HQSys;
var HQSys = require("./HsServerProxy.js").HQSys;
var servant = 'HQWeb.HsServer.HsServerObj';
if (!process.env.TAF_CONFIG) {
    //servant += "@tcp -h 127.0.0.1 -p 14009 -t 60000";
    servant += "@tcp -h 172.16.8.185 -t 60000 -p 10022";
}

var prx = Taf.stringToProxy(HQSys.BasicHqProxy, servant);


News.NewsInterfImp.prototype.initialize = function ( ) {
    //TODO::

}

News.NewsInterfImp.prototype.getMarketVane = function (current, marketVaneRsp) {
    logger.newsserver.info('-------------->Execute getMarketVane');
    var marketVaneRsp = new News.MarketVaneRsp();
    try{
        var marketVaneArray = global.MarketVane;
        var predictmap =global.MarketPredict;
        if(marketVaneArray===undefined){
            logger.newsserver.info('getMarketVane no data');
            marketVaneRsp.iRet=0;
            marketVaneRsp.iMsg='请求无数据';
            current.sendResponse(0, marketVaneRsp);
            return;
        };

        var vaneMap = {};
        var req_array=[];
        marketVaneArray.forEach(marketVane=>{
            var stockCode = marketVane.gpcode.substr(2,marketVane.gpcode.length);
            var market =marketVane.gpcode.substr(0,2)=='SH'?1:0;
            var vane = marketVane.vane;
            var advise='';
            if(vane==1){
                advise='较重仓位，波段操作';
            }else if(vane==2){
                advise='适度仓位、高抛低吸';
            }else{
                advise='轻仓、短线操作';
            }
            var upprob=0;
            var flucFlor=0;
            var flucCeil=0;
            var flucPrice=0;
            var predictJsonStr =predictmap[5+stockCode];
            var predictJsonArray=[]
            if(predictJsonStr!=undefined){
                predictJsonArray=JSON.parse(predictJsonStr);
            }
            predictJsonArray.forEach(predictJson=>{
                if(predictJson.HOLD_RANGE_PAR==1){
                    upprob=predictJson.UP_PROB;
                    flucFlor=predictJson.FLUC_FLOR;
                    flucCeil=predictJson.FLUC_CEIL;
                    flucPrice=predictJson.PRICE_PROG;
                }
            })
            var jsonObj={
                stockCode:stockCode,
                market:market,
                vane:vane,
                advise:advise,
                upprob:upprob,
                flucFlor:flucFlor,
                flucCeil:flucCeil,
                flucPrice:flucPrice,
                fullPosition:marketVane.fullPosition,
                advisePosition:marketVane.advisePosition
            };
            var reqObj={shtSetcode:market,sCode:stockCode};
            req_array.push(reqObj);
            var key =market+'_'+stockCode;
            vaneMap[key]=jsonObj;
        });
        var stockHqReq = new HQSys.StockHqReq();
        stockHqReq.vStock.readFromObject(req_array);
        prx.stockHq(stockHqReq).then(function(ret){
            var status = ret.response.return;
                if(status===0){
                    var vStockHq = ret.response.arguments.stRsp.vStockHq.value;
                    var vaneArray=[];
                    vStockHq.forEach(vStock=>{
                         var stockCode=vStock.sCode;
                         var market =vStock.shtSetcode;
                         var price = vStock.stSimHq.fNowPrice;
                         var zd = vStock.stSimHq.fChgValue;
                         var zdf = vStock.stSimHq.fChgRatio;
                         var key =market+'_'+stockCode;
                         var jsonObj =vaneMap[key];
                         jsonObj.zd=zd;
                         jsonObj.zdf=zdf;
                         jsonObj.price=price;
                         vaneArray.push(jsonObj);
                    });
                    marketVaneRsp.iRet=0;
                    marketVaneRsp.iMsg='SUCCESS';
                    marketVaneRsp.marketVaneList.readFromObject(vaneArray);
                    current.sendResponse(0, marketVaneRsp);
                    return;
                }else{
                    logger.newsserver.info('getMarketVane exception',status);
                    marketVaneRsp.iRet=-100;
                    marketVaneRsp.iMsg='请求异常';
                    current.sendResponse(-100, marketVaneRsp);
                    return;
                }
            }, function(err){
                logger.newsserver.info('getMarketVane exception',err);
                marketVaneRsp.iRet=-100;
                marketVaneRsp.iMsg='请求异常';
                current.sendResponse(-100, marketVaneRsp);
                return;
            }
        );

    }catch(e){
        logger.newsserver.info('getMarketVane exception',e);
        marketVaneRsp.iRet=-100;
        marketVaneRsp.iMsg='请求异常';
        current.sendResponse(-100, marketVaneRsp);
        return;
    }
}


News.NewsInterfImp.prototype.getSubJects = function (current, stReq, stRsp) {
    logger.newsserver.info('-------------->Execute getSubJects');
    var subJectsRsp = new News.SubJectsRsp();
    try{
        if(!stReq.sortType){
            logger.newsserver.info('缺少请求参数');
            subJectsRsp.iRet=-100;
            subJectsRsp.iMsg='缺少请求参数';
            current.sendResponse(-100, subJectsRsp);
            return;
        }
        var subJectsMap = global.SubJectsMap;
        if(subJectsMap===undefined){
            logger.newsserver.info('getSubJects no data');
            subJectsRsp.iRet=0;
            subJectsRsp.iMsg='请求无数据';
            current.sendResponse(0, subJectsRsp);
            return;
        };
        var global_subJectsArray=subJectsMap['SUBJECTSINFO_'+stReq.sortType];
        var subJectArray =[];
        global_subJectsArray.forEach(subJectInfo=>{
            var stockList =JSON.parse(subJectInfo.stk);
            var stockArray=[];
            if(stockList!=undefined){
                stockList.forEach(stock=>{
                    var stockCode = stock.key.substr(4,stock.key.length);
                    var market =stock.key.substr(0,4)=='0100'?1:0;
                    var stockObj={
                        stockCode:stockCode,
                        stockName:stock.sname,
                        market:market,
                        price:stock.price,
                        zdf:stock.zdf,
                        zd:stock.zd
                    }
                    stockArray.push(stockObj);
                })
            }
            var jsonObj={
                code:subJectInfo.code,
                name:subJectInfo.name,
                newsId:subJectInfo.news_id,
                title:subJectInfo.title,
                rankDate:moment(subJectInfo.ranking_date).format('YYYY-MM-DD'),
                hot:subJectInfo.hot_index,
                chgRatio:subJectInfo.chg_ratio,
                type:subJectInfo.type,
                stockList:stockArray
            }
            subJectArray.push(jsonObj);

        });
        subJectsRsp.iRet=0;
        subJectsRsp.iMsg='SUCCESS';
        if(subJectArray!=undefined&&subJectArray.length>0){
            subJectsRsp.subJectList.readFromObject(subJectArray);
        }
        current.sendResponse(0, subJectsRsp);
        return;
    }catch(e){
        logger.newsserver.info('getSubJects exception',e);
        subJectsRsp.iRet=-100;
        subJectsRsp.iMsg='请求异常';
        current.sendResponse(-100, subJectsRsp);
        return;
    }

}

News.NewsInterfImp.prototype.getLhbNews = function (current, stReq, stRsp) {
    logger.newsserver.info('-------------->Execute getLhbNews');
    var lhbNewsRsp = new News.LhbNewsRsp();
    try{
        if(!stReq){
            logger.newsserver.info('缺少请求参数');
            lhbNewsRsp.iRet=-100;
            lhbNewsRsp.iMsg='缺少请求参数';
            current.sendResponse(-100, lhbNewsRsp);
            return;
        }



        //var http_url = config.url.LHB_TODAY_URL;
        //if(http_url===undefined){
        //    logger.newsserver.info('龙虎榜数据 no data');
        //    lhbNewsRsp.iRet=-100;
        //    lhbNewsRsp.iMsg='龙虎榜数据 no data';
        //    current.sendResponse(-100, lhbNewsRsp);
        //    return;
        //}
        var result = global.LHBNewsData;
        if(result==undefined){
            lhbNewsRsp.iRet=0;
            lhbNewsRsp.iMsg='SUCCESS';
            current.sendResponse(0, lhbNewsRsp);
            return;
        }else{
            //交易状态
            lhbNewsRsp.tradeStatus=result.tradeStatus;
            var lhbArray=[];
            var jsonArray =result.orderbyrise.list;

            jsonArray.forEach(jsonObj=>{
                if(jsonObj.is_bull===stReq.type){
                    var stock_list = jsonObj.stock_list;
                    var theme_list = jsonObj.theme_list;
                    var stockArray=[];
                    var themeArray=[];
                    stock_list.forEach(stock=>{
                        var stockObj={
                            code:stock.SCode,
                            name:stock.SName,
                            market:+stock.Smarket,
                            reason:stock.Reason,
                            price:+stock.price,
                            zdf:+stock.change_rate
                        };
                        stockArray.push(stockObj);
                    });
                    theme_list.forEach(theme=>{
                        var themeObj={
                            code:theme.code,
                            name:theme.TName,
                            price:+theme.price,
                            zdf:+theme.change_rate
                        };
                        themeArray.push(themeObj);
                    });
                    var lhbObj ={
                        topicId: jsonObj.topic_id,
                        title:jsonObj.title,
                        valueTrend:jsonObj.value_trend,
                        time:jsonObj.update_time,
                        isBull:jsonObj.is_bull,
                        themeList:themeArray,
                        stockList:stockArray,
                        upNum:jsonObj.riseCount,
                        downNum:jsonObj.downCount,
                        drzf:jsonObj.averageChangeRate
                    };
                    lhbArray.push(lhbObj);
                };
            });
            if(stReq.type==1){
                common.sortByKeyDesc(lhbArray,'drzf');
            }else{
                common.sortByKey(lhbArray,'drzf');
            }
            lhbNewsRsp.iRet=0;
            lhbNewsRsp.iMsg='SUCCESS';
            lhbNewsRsp.lhbNewsList.readFromObject(lhbArray);
            current.sendResponse(0, lhbNewsRsp);
            return;
        }


        //common.getHttpData(http_url).then(
        //    function(result){
        //
        //    },function(err){
        //        logger.newsserver.info('getLhbNews 请求HTTP异常',err);
        //        lhbNewsRsp.iRet=-100;
        //        lhbNewsRsp.iMsg='请求HTTP异常';
        //        current.sendResponse(0, lhbNewsRsp);
        //        return;
        //    }
        //).done();

    }catch(e){
        logger.newsserver.info('getLhbNews exception',e);
        lhbNewsRsp.iRet=-100;
        lhbNewsRsp.iMsg='请求异常';
        current.sendResponse(-100, lhbNewsRsp);
        return;
    }
}

News.NewsInterfImp.prototype.getLhbHistory = function (current, stReq, stRsp) {
    logger.newsserver.info('-------------->Execute getLhbHistory');
    var lhbHistorysRsp = new News.LhbHistorysRsp();
    try{
        if(!stReq){
            logger.newsserver.info('缺少请求参数');
            lhbHistorysRsp.iRet=-100;
            lhbHistorysRsp.iMsg='缺少请求参数';
            current.sendResponse(-100, lhbHistorysRsp);
            return;
        }
        var startDate=stReq.startDate;
        var endDate = stReq.endDate;
        var wantNum =stReq.wantNum||20;
        var beginTime =stReq.beginTime;
        var lastNewsTime =stReq.lastNewsTime;
        var offset=stReq.offset||0;
        var http_url = config.url.LHB_HISTORY_URL;
        var isFirstPage = false;
        if((startDate!=undefined&&startDate!='')&&(endDate!=undefined&&endDate!='')){
            let default_startDate = moment().subtract('30', 'days').format('YYYY-MM-DD');
            let default_endDate = moment().subtract('1', 'days').format('YYYY-MM-DD');
            if(startDate==default_startDate&&endDate==default_endDate){
                isFirstPage=true;
            }
            http_url=http_url+'?offset='+offset+'&begin='+startDate+'&end='+endDate+'&pageSize='+wantNum;
        }else if((beginTime!=undefined&&beginTime!='')&&(lastNewsTime!=undefined&&lastNewsTime!='')){
            http_url=http_url+'?offset='+offset+'&pageSize='+wantNum+'&beginTime='+beginTime+'&lastNewsTimeStamp='+lastNewsTime;
        }
        if(http_url===undefined){
            logger.newsserver.info('龙虎榜历史数据 no data');
            lhbHistorysRsp.iRet=-100;
            lhbHistorysRsp.iMsg='龙虎榜历史数据 no data';
            current.sendResponse(-100, lhbHistorysRsp);
            return;
        }
        //取缓存
        if(isFirstPage){
            var result = global.LHBNewsHistoryData;
            if(result==undefined){
                lhbHistorysRsp.iRet=0;
                lhbHistorysRsp.iMsg='SUCCESS';
                current.sendResponse(0, lhbHistorysRsp);
                return;
            }else{
                //交易状态
                lhbHistorysRsp.tradeStatus=result.tradeStatus;
                lhbHistorysRsp.hasNext=result.hasNext;
                lhbHistorysRsp.beginTime=result.beginTime;
                lhbHistorysRsp.total=result.total;
                var lhbArray=[];
                var jsonArray =result.rankingHistoryByTime;
                jsonArray.forEach(jsonObj=>{
                    var stock_list = jsonObj.stock_list;
                    var theme_list = jsonObj.theme_list;
                    var stockArray=[];
                    var themeArray=[];
                    stock_list.forEach(stock=>{
                        var stockObj={
                            code:stock.SCode,
                            name:stock.SName,
                            market:+stock.Smarket,
                            reason:stock.Reason,
                            price:+stock.price,
                            zdf:+stock.change_rate
                        };
                        stockArray.push(stockObj);
                    });
                    theme_list.forEach(theme=>{
                        var themeObj={
                            code:theme.code,
                            name:theme.TName,
                            price:+theme.price,
                            zdf:+theme.change_rate
                        };
                        themeArray.push(themeObj);
                    });
                    var lhbObj ={
                        topicId: jsonObj.topic_id,
                        title:jsonObj.title,
                        valueTrend:jsonObj.value_trend,
                        time:jsonObj.update_time,
                        isBull:jsonObj.is_bull,
                        themeList:themeArray,
                        stockList:stockArray,
                        upNum:jsonObj.rise_count,
                        downNum:jsonObj.down_count,
                        drzf:jsonObj.average_changeRate,
                        frzf:jsonObj.fivedays_changeRate,
                        trzf:jsonObj.tendays_changeRate,
                        tyrzf:jsonObj.twentydays_changeRate
                    };
                    lhbArray.push(lhbObj);
                });
                lhbHistorysRsp.iRet=0;
                lhbHistorysRsp.iMsg='SUCCESS';
                lhbHistorysRsp.lhbNewsList.readFromObject(lhbArray);
                current.sendResponse(0, lhbHistorysRsp);
                return;
            }

        }else{
            common.getHttpData(http_url).then(
                function(result){
                    //交易状态
                    lhbHistorysRsp.tradeStatus=result.tradeStatus;
                    lhbHistorysRsp.hasNext=result.hasNext;
                    lhbHistorysRsp.beginTime=result.beginTime;
                    lhbHistorysRsp.total=result.total;
                    var lhbArray=[];
                    var jsonArray =result.rankingHistoryByTime;
                    jsonArray.forEach(jsonObj=>{
                        var stock_list = jsonObj.stock_list;
                        var theme_list = jsonObj.theme_list;
                        var stockArray=[];
                        var themeArray=[];
                        stock_list.forEach(stock=>{
                            var stockObj={
                                code:stock.SCode,
                                name:stock.SName,
                                market:+stock.Smarket,
                                reason:stock.Reason,
                                price:+stock.price,
                                zdf:+stock.change_rate
                            };
                            stockArray.push(stockObj);
                        });
                        theme_list.forEach(theme=>{
                            var themeObj={
                                code:theme.code,
                                name:theme.TName,
                                price:+theme.price,
                                zdf:+theme.change_rate
                            };
                            themeArray.push(themeObj);
                        });
                        var lhbObj ={
                            topicId: jsonObj.topic_id,
                            title:jsonObj.title,
                            valueTrend:jsonObj.value_trend,
                            time:jsonObj.update_time,
                            isBull:jsonObj.is_bull,
                            themeList:themeArray,
                            stockList:stockArray,
                            upNum:jsonObj.rise_count,
                            downNum:jsonObj.down_count,
                            drzf:jsonObj.average_changeRate,
                            frzf:jsonObj.fivedays_changeRate,
                            trzf:jsonObj.tendays_changeRate,
                            tyrzf:jsonObj.twentydays_changeRate
                        };
                        lhbArray.push(lhbObj);
                    });
                    lhbHistorysRsp.iRet=0;
                    lhbHistorysRsp.iMsg='SUCCESS';
                    lhbHistorysRsp.lhbNewsList.readFromObject(lhbArray);
                    current.sendResponse(0, lhbHistorysRsp);
                    return;
                },function(err){
                    logger.newsserver.info('getLhbHistory 请求HTTP异常',err);
                    lhbHistorysRsp.iRet=-100;
                    lhbHistorysRsp.iMsg='请求HTTP异常';
                    current.sendResponse(0, lhbHistorysRsp);
                    return;
                }
            ).done();
        }
    }catch(e){
        logger.newsserver.info('getLhbHistory exception',e);
        lhbHistorysRsp.iRet=-100;
        lhbHistorysRsp.iMsg='请求异常';
        current.sendResponse(-100, lhbHistorysRsp);
        return;
    }

}



News.NewsInterfImp.prototype.getSubJectsChart = function (current, stRsp) {
    logger.newsserver.info('-------------->Execute getSubJectsChart');
    var subJectChartRsp = new News.SubJectChartRsp();
    try{
        var subJectsMap = global.SubJectsMap;
        var stockHotMap = global.HotStock;
        var stockPlateMap = global.StockPlate;
        if(subJectsMap===undefined||stockHotMap===undefined||stockPlateMap===undefined){
            logger.newsserver.info('getSubJectsChart no data');
            subJectChartRsp.iRet=0;
            subJectChartRsp.iMsg='请求无数据';
            current.sendResponse(0, subJectChartRsp);
            return;
        };
        //取热门题材气泡图数据
        var global_subJectsArray=subJectsMap['SUBJECTSINFO_1'];
        var dataObj=[];
        var dataObj1=[];
        var subjectCodes=[];

        //取题材行情
        var subJectsHqReqArray=[];
        global_subJectsArray.forEach(subJectInfo=>{
            var jsonObj={
                code:subJectInfo.code,
                hotIndex:+subJectInfo.hot_index,
                name:subJectInfo.name,
                zf:subJectInfo.chg_ratio
            }
            var market = subJectInfo.code.substr(0,4)=='0100'?1:0;
            var stock=subJectInfo.code.substr(4,subJectInfo.code.length);
            subJectsHqReqArray.push({shtSetcode:market,sCode:stock});

            subjectCodes.push(subJectInfo.code);
            dataObj.push(jsonObj);
        });
        var hotStockArray=[];
        var hotIndexMap =[];
        subjectCodes.forEach(subjectCode=>{
            var stockCodeArray= JSON.parse(stockPlateMap[subjectCode]);
            var stockArray=[];

            stockCodeArray.forEach(stock=>{
                //股票代码 stockCode
                //热度
                var hotIndex=stockHotMap[stock.CONC_RELA_STK]===undefined?0:stockHotMap[stock.CONC_RELA_STK].STK_HOT_INDEX;
                var stockObj={
                    stockCode:stock.CONC_RELA_STK,
                    hotIndex:hotIndex
                }
                hotIndexMap[stock.CONC_RELA_STK]=hotIndex;
                stockArray.push(stockObj);
            });

            common.sortByKeyDesc(stockArray,'hotIndex');
            //如果板块成分股不足5只 则取固定指数上证指数（000001）填充
            if(stockArray.length<5){
                 for(var i=stockArray.length;i<5;i++){
                     stockArray.push({'stockCode':'0100000001','hotIndex':0});
                 }
            }
            hotStockArray=hotStockArray.concat(stockArray.slice(0,5));
        });
        //查询hotStockArray 的行情
        var array=[];
        hotStockArray.forEach(hotStock=>{
            var market = hotStock.stockCode.substr(0,4)=='0100'?1:0;
            var stock=hotStock.stockCode.substr(4,hotStock.stockCode.length);
            array.push({shtSetcode:market,sCode:stock});
        })
        var stockHqReq = new HQSys.StockHqReq();
        stockHqReq.vStock.readFromObject(array);
        prx.stockHq(stockHqReq).then(function(ret){
            var status = ret.response.return;
            if(status===0){
                var vStockHq = ret.response.arguments.stRsp.vStockHq.value;
                vStockHq.forEach(stock=>{
                    var code = stock.shtSetcode==1?'0100'+stock.sCode:'0000'+stock.sCode;
                    var hotIndex =hotIndexMap[code];
                    var stockJson={
                        code:code,
                        hotIndex:+hotIndex,
                        name:stock.sName,
                        zf:stock.stSimHq.fChgRatio
                     };
                     if(code=='0100000001'){
                         stockJson={
                             code:'0',
                             hotIndex:0,
                             name:'0',
                             zf:0
                         }
                     }
                     dataObj1.push(stockJson);
                });
                var subjectHqReq = new   HQSys.StockHqReq();
                subjectHqReq.vStock.readFromObject(subJectsHqReqArray);
                prx.stockHq(subjectHqReq).then(function(ret){
                    var status = ret.response.return;
                    if(status===0){
                        var vStockHq = ret.response.arguments.stRsp.vStockHq.value;
                        for(var i=0;i<dataObj.length;i++){
                            vStockHq.forEach(stock=>{
                                var code = stock.shtSetcode==1?'0100'+stock.sCode:'0000'+stock.sCode;
                                if(code==dataObj[i].code){
                                    dataObj[i].zf=stock.stSimHq.fChgRatio;
                                }
                            });
                        };
                        var jsonObj = {
                            data:'',
                            dataObj:dataObj,
                            dataObj1:dataObj1,
                            dataObj2:null,
                            dataObj3:null,
                            flag:true,
                            msg:'成功'
                        };
                        subJectChartRsp.iRet=0;
                        subJectChartRsp.iMsg='SUCCESS';
                        subJectChartRsp.dataJsonStr=JSON.stringify(jsonObj);
                        current.sendResponse(0, subJectChartRsp);
                        return;


                    }else{
                        logger.newsserver.info('getSubJectsChart exception',status);
                        subJectChartRsp.iRet=-100;
                        subJectChartRsp.iMsg='请求异常';
                        current.sendResponse(-100, subJectChartRsp);
                        return;
                    }
                }, function(err){
                    logger.newsserver.info('getSubJectsChart exception',err);
                    subJectChartRsp.iRet=-100;
                    subJectChartRsp.iMsg='请求异常';
                    current.sendResponse(-100, subJectChartRsp);
                    return;
                }).done();

            }else{
                logger.newsserver.info('getSubJectsChart exception',status);
                subJectChartRsp.iRet=-100;
                subJectChartRsp.iMsg='请求异常';
                current.sendResponse(-100, subJectChartRsp);
                return;
            }

        }, function(err){
            logger.newsserver.info('getSubJectsChart exception',err);
            subJectChartRsp.iRet=-100;
            subJectChartRsp.iMsg='请求异常';
            current.sendResponse(-100, subJectChartRsp);
            return;
        }).done();
    }catch(e){
        logger.newsserver.info('getSubJectsChart exception',e);
        subJectChartRsp.iRet=-100;
        subJectChartRsp.iMsg='请求异常';
        current.sendResponse(-100, subJectChartRsp);
        return;
    }

}


News.NewsInterfImp.prototype.getTopLhbNews = function (current, stRsp) {
    logger.newsserver.info('-------------->Execute getTopLhbNews');
    var lhbNewsRsp = new News.TopLhbNewsRsp();
    try{
        var http_url = config.url.LHB_TODAY_URL;
        if(http_url===undefined){
            logger.newsserver.info('TOP龙虎榜数据 no data');
            lhbNewsRsp.iRet=-100;
            lhbNewsRsp.iMsg='TOP龙虎榜数据 no data';
            current.sendResponse(-100, lhbNewsRsp);
            return;
        }
        var result = global.LHBNewsData;
        if(result==undefined){
            lhbNewsRsp.iRet=0;
            lhbNewsRsp.iMsg='SUCCESS';
            current.sendResponse(0, lhbNewsRsp);
            return;
        }else{
            //交易状态
            lhbNewsRsp.tradeStatus=result.tradeStatus;
            var lhbArrayLD=[];
            var lhbArrayLK=[];
            var jsonArray =result.orderbyrise.list;
            jsonArray.forEach(jsonObj=>{

                var stock_list = jsonObj.stock_list;
                var theme_list = jsonObj.theme_list;
                var stockArray=[];
                var themeArray=[];
                stock_list.forEach(stock=>{
                    var stockObj={
                        code:stock.SCode,
                        name:stock.SName,
                        market:+stock.Smarket,
                        reason:stock.Reason,
                        price:+stock.price,
                        zdf:+stock.change_rate
                    };
                    stockArray.push(stockObj);
                });
                theme_list.forEach(theme=>{
                    var themeObj={
                        code:theme.code,
                        name:theme.TName,
                        price:+theme.price,
                        zdf:+theme.change_rate
                    };
                    themeArray.push(themeObj);
                });
                var lhbObj ={
                    topicId: jsonObj.topic_id,
                    title:jsonObj.title,
                    valueTrend:jsonObj.value_trend,
                    time:jsonObj.update_time,
                    isBull:jsonObj.is_bull,
                    themeList:themeArray,
                    stockList:stockArray,
                    upNum:jsonObj.riseCount,
                    downNum:jsonObj.downCount,
                    drzf:jsonObj.averageChangeRate
                };
                if(jsonObj.is_bull===1){
                    lhbArrayLD.push(lhbObj);
                };
                if(jsonObj.is_bull===0){
                    lhbArrayLK.push(lhbObj);
                }
            });

            var topLhbArrayLD=[];
            var topLhbArrayLK=[];
            common.sortByKeyDesc(lhbArrayLD,'drzf');
            common.sortByKey(lhbArrayLK,'drzf');
            if(lhbArrayLD.length>3){
                topLhbArrayLD=lhbArrayLD.slice(0,3);
            }else{
                topLhbArrayLD=lhbArrayLD;
            }
            if(lhbArrayLK.length>3){
                topLhbArrayLK=lhbArrayLK.slice(0,3);
            }else{
                topLhbArrayLK=lhbArrayLK;
            }
            lhbNewsRsp.iRet=0;
            lhbNewsRsp.iMsg='SUCCESS';
            lhbNewsRsp.lhbNewsListLD.readFromObject(topLhbArrayLD);
            lhbNewsRsp.lhbNewsListLK.readFromObject(topLhbArrayLK);
            current.sendResponse(0, lhbNewsRsp);
            return;
        }
        //common.getHttpData(http_url).then(
        //    function(result){
        //
        //    },function(err){
        //        logger.newsserver.info('getLhbNews 请求HTTP异常',err);
        //        lhbNewsRsp.iRet=-100;
        //        lhbNewsRsp.iMsg='请求HTTP异常';
        //        current.sendResponse(0, lhbNewsRsp);
        //        return;
        //    }
        //).done();

    }catch(e){
        logger.newsserver.info('getLhbNews exception',e);
        lhbNewsRsp.iRet=-100;
        lhbNewsRsp.iMsg='请求异常';
        current.sendResponse(-100, lhbNewsRsp);
        return;
    }

}




News.NewsInterfImp.prototype.getHotDayStock = function (current, stRsp) {
    logger.newsserver.info('-------------->Execute getHotDayStock');
    var hotDayStockRsp = new News.HotDayStockRsp();
    try{
        //每日热股数据
        var dayStockArray = global.DayStock;
        //股票当日热度
        var stockHotDayMap = global.HotStock;
        //股票历史热度
        var stockHotHistoryMap = global.HotStockHistory;
        //股票相关题材
        var stockRelaPlateMap = global.StockRelaPlate;
        if(dayStockArray===undefined||stockHotDayMap===undefined||stockHotHistoryMap===undefined||stockRelaPlateMap===undefined){
            logger.newsserver.info('getHotDayStock no data');
            hotDayStockRsp.iRet=0;
            hotDayStockRsp.iMsg='请求无数据';
            current.sendResponse(0, hotDayStockRsp);
            return;
        };

        var req_array=[];
        dayStockArray.forEach(dayStock=>{
            var market = dayStock.STK_CODE.substr(0,4)=='0100'?1:0;
            var stock=dayStock.STK_CODE.substr(4,dayStock.STK_CODE.length);
            req_array.push({shtSetcode:market,sCode:stock});
        })
        var stockHqReq = new HQSys.StockHqReq();
        stockHqReq.vStock.readFromObject(req_array);
        prx.stockHq(stockHqReq).then(function(ret) {
            var status = ret.response.return;
            if (status === 0) {
                var hotstockArray=[];
                var vStockHq = ret.response.arguments.stRsp.vStockHq.value;
                vStockHq.forEach(stock=> {
                    var code = stock.shtSetcode == 1 ? '0100' + stock.sCode : '0000' + stock.sCode;
                    var hotIndex = stockHotDayMap[code]==undefined?0:stockHotDayMap[code].STK_HOT_INDEX;
                    var hotIndexRatio =stockHotDayMap[code]==undefined?0:stockHotDayMap[code].HOT_INDEX_CHG_RATIO;
                    var date =stockHotDayMap[code]==undefined?'':stockHotDayMap[code].COUNT_DATE.length>10?stockHotDayMap[code].COUNT_DATE.substr(0,10):stockHotDayMap[code].COUNT_DATE;
                    var hotHistoryArray =eval(stockHotHistoryMap[code]);
                    var stockRelaPlateArray = eval(stockRelaPlateMap[code]);
                    var hotChartArray =[];
                    var themeArray=[];
                    hotHistoryArray.forEach(hotHistory=>{
                          var obj = {
                              code:hotHistory.STK_CODE,
                              date:hotHistory.COUNT_DATE.length>10?hotHistory.COUNT_DATE.substr(0,10):hotHistory.COUNT_DATE,
                              hot:hotHistory.STK_HOT_INDEX
                          };
                          hotChartArray.push(obj);
                    });
                    //将最新的一天的热度也加入走势图 并排序
                    hotChartArray.push({code:code,date:date,hot:hotIndex});
                    common.sortByKey(hotChartArray,'date');
                    stockRelaPlateArray.forEach(stockRelaPlate=>{
                         var obj ={
                             code:stockRelaPlate.CODE,
                             name:stockRelaPlate.NAME,
                             price:0,
                             zdf:0
                         }
                        themeArray.push(obj);
                    });
                    var stockJson = {
                        code: stock.sCode,
                        name: stock.sName,
                        market:stock.shtSetcode,
                        price:stock.stSimHq.fNowPrice,
                        zdf: stock.stSimHq.fChgRatio,
                        hot: hotIndex,
                        chgRatio:hotIndexRatio,
                        themeList:themeArray,
                        hotChartList:hotChartArray
                    };
                    hotstockArray.push(stockJson);
                });
                common.sortByKeyDesc(hotstockArray,'hotIndex');
                hotDayStockRsp.iRet=0;
                hotDayStockRsp.iMsg='SUCCESS';
                hotDayStockRsp.hotDayList.readFromObject(hotstockArray);
                current.sendResponse(0, hotDayStockRsp);
                return;
            } else {
                logger.newsserver.info('getHotDayStock exception', status);
                hotDayStockRsp.iRet = -100;
                hotDayStockRsp.iMsg = '请求异常';
                current.sendResponse(-100, hotDayStockRsp);
                return;
            }
         } , function(err){
                logger.newsserver.info('getHotDayStock exception',err);
                hotDayStockRsp.iRet=-100;
                hotDayStockRsp.iMsg='请求异常';
                current.sendResponse(-100, hotDayStockRsp);
                return;
         });
    }catch(e){
        logger.newsserver.info('getHotDayStock exception',e);
        hotDayStockRsp.iRet=-100;
        hotDayStockRsp.iMsg='请求异常';
        current.sendResponse(-100, hotDayStockRsp);
        return;
    }

}

//获取个股周K线
function getStockWeekKLine(json){
    logger.newsserver.info('=====>查询个股最后周K线......')
    var deferred = Q.defer();
    try{
        var kLineDataReq = new HQSys.KLineDataReq();
        kLineDataReq.market=json.shtSetcode;
        kLineDataReq.sCode=json.sCode;
        kLineDataReq.eLineType=Common_HQSys.HISTORY_DATA_TYPE.HDT_WEEK_KLINE;
        kLineDataReq.shtStartxh=0;
        kLineDataReq.shtWantNum=2;
        prx.kLineData(kLineDataReq).then(
            function(ret){
                var status = ret.response.return;
                if(status===0){
                    var vAnalyData = ret.response.arguments.stRsp.vAnalyData.value;
                    if(vAnalyData.length==0){
                        deferred.resolve({shtSetcode:json.shtSetcode,sCode:json.sCode,profit:0});
                    }else{
                        var fOpen=0;
                        var fClose=0;
                        var profit=0;
                        if(vAnalyData.length<2){
                              fOpen = vAnalyData[0].fOpen;
                              fClose =vAnalyData[0].fClose;
                        }else{

                              fOpen = vAnalyData[0].fClose;
                              fClose = vAnalyData[1].fClose;
                        }
                        profit = ((fClose-fOpen)/fOpen).toFixed(6);
                        deferred.resolve({shtSetcode:json.shtSetcode,sCode:json.sCode,profit:profit});
                    }
                }
            }, function(err){
                console.log(err);
                deferred.reject(err);
            }
        ).done();
    }catch(e){
        deferred.reject(e);
    }
    return deferred.promise;
}

function getWeekProfit(req_array){

    logger.newsserver.info('=====>查询个股本周收益......')
    var deferred = Q.defer();
    try{
        Q.all(req_array.map(req_json=>getStockWeekKLine(req_json))).then(
            function(results){
                var weekProfitMap={};
                results.forEach(profitJson=>{
                    var key = profitJson.shtSetcode==1?'0100'+profitJson.sCode:'0000'+profitJson.sCode;
                    var value = profitJson.profit;
                    weekProfitMap[key]=profitJson;
                });
                deferred.resolve(weekProfitMap);
            },function(err){
                deferred.reject(err);
            }
        ).done();
    }catch(e){
        deferred.reject(e);
    }
    return deferred.promise;
}

News.NewsInterfImp.prototype.getHotWeekStock = function (current, stRsp) {
    logger.newsserver.info('-------------->Execute getHotWeekStock');
    var hotWeekStockRsp = new News.HotWeekStockRsp();
    try{
        var hotWeekArray=[];
        //周牛股中存在的最大交易日的牛股数据
        var maxHotWeekStockArray = global.MaxHotWeekStock;
        //股票相关题材
        var stockRelaPlateMap = global.StockRelaPlate;
        if(maxHotWeekStockArray===undefined||stockRelaPlateMap===undefined){
            logger.newsserver.info('getHotWeekStock no data');
            hotWeekStockRsp.iRet=0;
            hotWeekStockRsp.iMsg='请求无数据';
            current.sendResponse(0, hotWeekStockRsp);
            return;
        };
        var resultArray =[];
        if(maxHotWeekStockArray.length>0){
            //获取本周第一天与最后一天 -1代表上一个周  0代表本周   1代表下一个周
            var  weekDay = common.getWeekStartAndEnd(0)

            TradeDate.GetTradeDate(weekDay[0],weekDay[1]).then(
                function(res){
                    //本周是否存在交易日
                    var isTradeWeek=res.length>0;
                    var date =moment(maxHotWeekStockArray[0].Stock_Date).format('YYYYMMDD');

                    var req_array=[];
                    var profitMap = {};
                    maxHotWeekStockArray.forEach(weekStock=>{
                        var market = weekStock.STK_CODE.substr(0,4)=='0100'?1:0;
                        var stock=weekStock.STK_CODE.substr(4,weekStock.STK_CODE.length);
                        req_array.push({shtSetcode:market,sCode:stock});
                        profitMap[weekStock.STK_CODE]=weekStock;
                    });
                    var stockHqReq = new HQSys.StockHqReq();
                    stockHqReq.vStock.readFromObject(req_array);

                    //如果当周有交易日，检查最大日期的周荐股不在本周内，则表示本周未加荐股 展示空
                    if(isTradeWeek&&(date>weekDay[1]||date<weekDay[0])){
                        resultArray=[];
                        hotWeekStockRsp.iRet=0;
                        hotWeekStockRsp.iMsg='SUCCESS';
                        current.sendResponse(0, hotWeekStockRsp);
                        return;
                    }else if(isTradeWeek&&(date>=weekDay[0]&&date<=weekDay[1])){
                    //如果当周有交易日，并且荐股日期再本周内，展示荐股日期荐股数据
                        getWeekProfit(req_array).then(
                            function(result){
                                prx.stockHq(stockHqReq).then(function(ret) {
                                    var status = ret.response.return;
                                    if (status === 0) {
                                        var vStockHq = ret.response.arguments.stRsp.vStockHq.value;
                                        vStockHq.forEach(stock=> {
                                            var code = stock.shtSetcode == 1 ? '0100' + stock.sCode : '0000' + stock.sCode;
                                            var stockRelaPlateArray = eval(stockRelaPlateMap[code]);
                                            var weekProfit =(result[code].profit*100).toFixed(2);
                                            var themeArray=[];
                                            stockRelaPlateArray.forEach(stockRelaPlate=>{
                                                var obj ={
                                                    code:stockRelaPlate.CODE,
                                                    name:stockRelaPlate.NAME,
                                                    price:0,
                                                    zdf:0
                                                }
                                                themeArray.push(obj);
                                            });
                                            var stockJson = {
                                                code: stock.sCode,
                                                name: stock.sName,
                                                market:stock.shtSetcode,
                                                price:stock.stSimHq.fNowPrice,
                                                zdf: stock.stSimHq.fChgRatio,
                                                themeList:themeArray,
                                                weekProfit:weekProfit
                                            };
                                            resultArray.push(stockJson);
                                        });
                                        hotWeekStockRsp.iRet=0;
                                        hotWeekStockRsp.iMsg='SUCCESS';
                                        hotWeekStockRsp.hotWeekList.readFromObject(resultArray);
                                        current.sendResponse(0, hotWeekStockRsp);
                                        return;
                                    } else {
                                        logger.newsserver.info('GetTradeDate exception',status);
                                        hotWeekStockRsp.iRet=-100;
                                        hotWeekStockRsp.iMsg='请求异常';
                                        current.sendResponse(-100, hotWeekStockRsp);
                                        return;
                                    }
                                } , function(err){
                                    logger.newsserver.info('GetTradeDate exception',err);
                                    hotWeekStockRsp.iRet=-100;
                                    hotWeekStockRsp.iMsg='请求异常';
                                    current.sendResponse(-100, hotWeekStockRsp);
                                    return;
                                }).done();
                            },function(err){
                                logger.newsserver.info('GetTradeDate exception',err);
                                hotWeekStockRsp.iRet=-100;
                                hotWeekStockRsp.iMsg='请求异常';
                                current.sendResponse(-100, hotWeekStockRsp);
                                return;
                            }
                        ).done();
                    }else{
                        //如果当周内没有一个交易日 比如国庆节，春节等 则取上周的周牛股数据展示
                        prx.stockHq(stockHqReq).then(function(ret) {
                            var status = ret.response.return;
                            if (status === 0) {
                                var vStockHq = ret.response.arguments.stRsp.vStockHq.value;
                                vStockHq.forEach(stock=> {
                                    var code = stock.shtSetcode == 1 ? '0100' + stock.sCode : '0000' + stock.sCode;
                                    var stockRelaPlateArray = eval(stockRelaPlateMap[code]);
                                    var weekProfit =(profitMap[code].Week_Profit*100).toFixed(2);
                                    var themeArray=[];

                                    stockRelaPlateArray.forEach(stockRelaPlate=>{
                                        var obj ={
                                            code:stockRelaPlate.CODE,
                                            name:stockRelaPlate.NAME,
                                            price:0,
                                            zdf:0
                                        }
                                        themeArray.push(obj);
                                    });
                                    var stockJson = {
                                        code: stock.sCode,
                                        name: stock.sName,
                                        market:stock.shtSetcode,
                                        price:stock.stSimHq.fNowPrice,
                                        zdf: stock.stSimHq.fChgRatio,
                                        themeList:themeArray,
                                        weekProfit:weekProfit
                                    };
                                    resultArray.push(stockJson);
                                });
                                hotWeekStockRsp.iRet=0;
                                hotWeekStockRsp.iMsg='SUCCESS';
                                hotWeekStockRsp.hotWeekList.readFromObject(resultArray);
                                current.sendResponse(0, hotWeekStockRsp);
                                return;
                            } else {
                                logger.newsserver.info('GetTradeDate exception',status);
                                hotWeekStockRsp.iRet=-100;
                                hotWeekStockRsp.iMsg='请求异常';
                                current.sendResponse(-100, hotWeekStockRsp);
                                return;
                            }
                        } , function(err){
                            logger.newsserver.info('GetTradeDate exception',err);
                            hotWeekStockRsp.iRet=-100;
                            hotWeekStockRsp.iMsg='请求异常';
                            current.sendResponse(-100, hotWeekStockRsp);
                            return;
                        }).done();
                    }

                },function(err){
                    logger.newsserver.info('GetTradeDate exception',err);
                    hotWeekStockRsp.iRet=-100;
                    hotWeekStockRsp.iMsg='请求异常';
                    current.sendResponse(-100, hotWeekStockRsp);
                    return;
                }
            ).done();
        }else{
            hotWeekStockRsp.iRet=0;
            hotWeekStockRsp.iMsg='SUCCESS';
            current.sendResponse(0, hotWeekStockRsp);
            return;
        }
    }catch(e){
        logger.newsserver.info('getHotWeekStock exception',e);
        hotWeekStockRsp.iRet=-100;
        hotWeekStockRsp.iMsg='请求异常';
        current.sendResponse(-100, hotWeekStockRsp);
        return;
    }
}


News.NewsInterfImp.prototype.getWeekHistoryStock = function (current,stReq, stRsp) {
    logger.newsserver.info('-------------->Execute getWeekHistoryStock');
    var weekHistoryRsp = new News.WeekHistoryRsp();
    try{
        if(!stReq){
            logger.newsserver.info('缺少请求参数');
            weekHistoryRsp.iRet=-100;
            weekHistoryRsp.iMsg='缺少请求参数';
            current.sendResponse(-100, weekHistoryRsp);
            return;
        }
        //数据库中周牛股历史记录
        var historyHotWeekStockList = global.HistoryHotWeekStock;
        console.log(historyHotWeekStockList.length);
        if(historyHotWeekStockList===undefined){
            logger.newsserver.info(' HistoryHotWeekStock no data ');
            weekHistoryRsp.iRet=-100;
            weekHistoryRsp.iMsg='HistoryHotWeekStock no data';
            current.sendResponse(-100, weekHistoryRsp);
            return;
        };

        var  weekHistoryArray=[];
        if(historyHotWeekStockList.length>0) {

            //获取本周第一天与最后一天 -1代表上一个周  0代表本周   1代表下一个周
            var weekDay = common.getWeekStartAndEnd(0)
            TradeDate.GetTradeDate(weekDay[0], weekDay[1]).then(
                function (res) {
                    //本周是否存在交易日
                    var isTradeWeek = res.length > 0;
                    var first_date =moment(historyHotWeekStockList[0].Stock_Date).format('YYYYMMDD');

                    var local_historyHotWeekStockList =historyHotWeekStockList;
                    if(isTradeWeek&&first_date>=weekDay[0]){
                        local_historyHotWeekStockList= historyHotWeekStockList.slice(1,historyHotWeekStockList.length);
                    }

                    var start = stReq.startNum;
                    var num = stReq.wantNum;
                    var pagesize_historyHotWeekStockList =local_historyHotWeekStockList.slice(start,start+num);

                    pagesize_historyHotWeekStockList.forEach(historyHotWeekStock=>{
                        var date = moment(historyHotWeekStock.STOCK_DATE).format('YYYY-MM-DD');
                        var weekProfit = 0;
                        var hsProfit=0;
                        var nums = 0;
                        var stockArray =eval(historyHotWeekStock.jsonArray);
                        var hotWeekStockArray=[];
                        if(stockArray.length>0&&stockArray[0].STK_CODE!=undefined){
                            stockArray.forEach(stock=>{
                                var market = stock.STK_CODE.substr(0,4)=='0100'?1:0;
                                var stockcode=stock.STK_CODE.substr(4,stock.STK_CODE.length);
                                var hotWeekStock={
                                      code:stockcode,
                                      name:stock.STK_NAME,
                                      market:market
                                };
                                hsProfit =stock.HS_WEEK_PROFIT;
                                weekProfit+=stock.WEEK_PROFIT;
                                nums =nums+1;
                                hotWeekStockArray.push(hotWeekStock);
                            });
                        }else if(stockArray.length>0&&stockArray.length<=1){
                            hsProfit =stockArray[0].HS_WEEK_PROFIT;
                        };
                        var obj ={
                            date:date,
                            weekProfit:(weekProfit/(nums==0?1:nums)).toFixed(4),
                            hsProfit:hsProfit,
                            stockList:hotWeekStockArray
                        }
                        weekHistoryArray.push(obj);

                    });
                    weekHistoryRsp.iRet=0;
                    weekHistoryRsp.iMsg='SUCCESS';
                    weekHistoryRsp.weekHistoryList.readFromObject(weekHistoryArray);
                    current.sendResponse(0, weekHistoryRsp);
                    return;
                }, function (err) {
                    logger.newsserver.info('getWeekHistoryStock err', err);
                    weekHistoryRsp.iRet = -100;
                    weekHistoryRsp.iMsg = '请求异常';
                    current.sendResponse(-100, weekHistoryRsp);
                    return;
                }
            ).done();
        }else{
            weekHistoryRsp.iRet=0;
            weekHistoryRsp.iMsg='SUCCESS';
            current.sendResponse(0, weekHistoryRsp);
            return;
        }




    }catch(e){
        logger.newsserver.info('getWeekHistoryStock exception',e);
        weekHistoryRsp.iRet=-100;
        weekHistoryRsp.iMsg='请求异常';
        current.sendResponse(-100, weekHistoryRsp);
        return;
    }
}