// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 4.2.1 by TAF Team.
// Generated from `./Market.jce'
// **********************************************************************

var TafStream = require('@taf/taf-stream');
var TafError  = require('@taf/taf-rpc').error;

if(TafStream.JceStruct == undefined){
TafStream.JceStruct = function() {
this._jce_double_precision_ = -1;
}
TafStream.JceStruct.prototype.setPrecision = function(d) {
if ((d == -1) || (d >= 0 && d <= 15)) {
this._jce_double_precision_ = d;
return true;
}
return false;
}
TafStream.JceStruct.prototype.resetPrecision = function() { this._jce_double_precision_ = -1;}
TafStream.JceStruct.prototype.hasSetPrecision = function() { return (this._jce_double_precision_ >= 0 && this._jce_double_precision_ <= 15);}
TafStream.JceStruct.prototype.getPrecision = function() { return this._jce_double_precision_; }
}

var Market = Market || {};
module.exports.Market = Market;

Market.WebHQProxy = function () {
    this._name   = undefined;
    this._worker = undefined;
}

Market.WebHQProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
}

Market.WebHQProxy.prototype.getTimeout = function ( ) {
    return this._worker.timeout;
}


Market.HISTORY_DATA_TYPE = {
    HDT_DAY_KLINE : 0,
    HDT_MIN1_KLINE : 1,
    HDT_MIN5_KLINE : 2,
    HDT_MIN15_KLINE : 3,
    HDT_MIN30_KLINE : 4,
    HDT_MIN60_KLINE : 5,
    HDT_RTMIN : 6,
    HDT_WEEK_KLINE : 7,
    HDT_MONTH_KLINE : 8,
    HDT_SEASON_KLINE : 9,
    HDT_YEAR_KLINE : 10,
    HDT_DAY_MONEYFLOW : 11,
    HDT_TICK : 12,
    HDT_WEEK_MONEYFLOW : 13,
    HDT_MONTH_MONEYFLOW : 14,
    HDT_SEASON_MONEYFLOW : 15,
    HDT_YEAR_MONEYFLOW : 16,
    HDT_FLOW_MIN1 : 17,
    HDT_FLOW_MIN5 : 18,
    HDT_FLOW_MIN15 : 19,
    HDT_FLOW_MIN30 : 20,
    HDT_FLOW_MIN60 : 21
};
Market.HISTORY_DATA_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
Market.HISTORY_DATA_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
Market.E_BUSS_TYPE = {
    EBT_A : 6,
    EBT_B : 7,
    EBT_JJ : 9,
    EBT_SH_A : 0,
    EBT_SH_B : 1,
    EBT_SH_ZQ : 4,
    EBT_SZ_A : 2,
    EBT_SZ_B : 3,
    EBT_SZ_CY : 18,
    EBT_SZ_SM : 12,
    EBT_SZ_ZQ : 5,
    EBT_ZQ : 8,
    EBT_BLK_HY : 32,
    EBT_BLK_DY : 31,
    EBT_BLK_GN : 33,
    EBT_BLK_ALL : 30,
    EBT_ZS_BK : 11,
    EBT_QZ : 17,
    EBT_ZJ : 23,
    EBT_SH_JJ : 9100,
    EBT_SZ_JJ : 9101,
    EBT_ZS : 10422,
    EBT_SH_ZS : 10423,
    EBT_SZ_ZS : 10424,
    EBT_M_BH : 19,
    EBT_M_TG : 26,
    EBT_M_SHJ : 24,
    EBT_M_GJJ : 25,
    EBT_M_DS : 20,
    EBT_M_ZS : 21,
    EBT_M_SQ : 22,
    EBT_M_DY : 34,
    EBT_M_GJ : 35,
    EBT_M_HSI : 49,
    EBT_M_US : 50,
    EBT_M_NASDAQ : 51,
    EBT_M_NYSE : 52,
    EBT_M_AMEX : 53,
    EBT_M_USI : 54,
    EBT_M_XS : 10500,
    EBT_M_FUND : 10350,
    EBT_M_CBOT : 10400,
    EBT_M_COMEX : 10401,
    EBT_M_NYMEX : 10402,
    EBT_M_LME : 10403,
    EBT_M_FX : 10410,
    EBT_M_CNY : 10412,
    EBT_T_HK : 36,
    EBT_T_HK_ZB : 37,
    EBT_T_HK_CYB : 38,
    EBT_T_HK_ZQ : 39,
    EBT_T_HK_QZ : 41,
    EBT_T_HK_NXZ : 42,
    EBT_T_HK_JJ : 43,
    EBT_T_SC_CU : 10000,
    EBT_T_SC_AL : 10001,
    EBT_T_SC_ZN : 10002,
    EBT_T_SC_PB : 10003,
    EBT_T_SC_AU : 10004,
    EBT_T_SC_AG : 10005,
    EBT_T_SC_RB : 10006,
    EBT_T_SC_RU : 10007,
    EBT_T_SC_FU : 10008,
    EBT_T_SC_WR : 10009,
    EBT_T_SC_BU : 10010,
    EBT_T_SC_HC : 10011,
    EBT_T_SC_NI : 10012,
    EBT_T_SC_SN : 10013,
    EBT_T_DC_A : 10100,
    EBT_T_DC_M : 10101,
    EBT_T_DC_Y : 10102,
    EBT_T_DC_P : 10103,
    EBT_T_DC_C : 10104,
    EBT_T_DC_I : 10105,
    EBT_T_DC_JM : 10106,
    EBT_T_DC_J : 10107,
    EBT_T_DC_L : 10108,
    EBT_T_DC_V : 10109,
    EBT_T_DC_B : 10110,
    EBT_T_DC_JD : 10111,
    EBT_T_DC_FB : 10112,
    EBT_T_DC_BB : 10113,
    EBT_T_DC_PP : 10114,
    EBT_T_DC_CS : 10115,
    EBT_T_ZC_WH : 10200,
    EBT_T_ZC_OI : 10201,
    EBT_T_ZC_CF : 10202,
    EBT_T_ZC_SR : 10203,
    EBT_T_ZC_RI : 10204,
    EBT_T_ZC_TC : 10205,
    EBT_T_ZC_TA : 10206,
    EBT_T_ZC_FG : 10207,
    EBT_T_ZC_MA : 10208,
    EBT_T_ZC_RM : 10209,
    EBT_T_ZC_RS : 10210,
    EBT_T_ZC_PM : 10211,
    EBT_T_ZC_JR : 10212,
    EBT_T_ZC_LR : 10213,
    EBT_T_ZC_SM : 10214,
    EBT_T_ZC_SF : 10215,
    EBT_TB : 10438,
    EBT_TB_ZS : 10439,
    EBT_TB_ZSZR : 10440,
    EBT_TB_XYZR : 10441,
    EBT_TB_LW : 10442,
    EBT_TB_DSC : 10443,
    EBT_TB_DGP : 10444,
    EBT_TB_YZB : 10445
};
Market.E_BUSS_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
Market.E_BUSS_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
Market.E_HQ_SORT_COLUMN = {
    E_HQ_COLUMN_CODE : 1,
    E_HQ_COLUMN_NAME : 2,
    E_HQ_COLUMN_YCLOSE : 3,
    E_HQ_COLUMN_OPEN : 4,
    E_HQ_COLUMN_HIGH : 5,
    E_HQ_COLUMN_LOW : 6,
    E_HQ_COLUMN_NOWPRICE : 7,
    E_HQ_COLUMN_BUY : 8,
    E_HQ_COLUMN_SELL : 9,
    E_HQ_COLUMN_VOLUME : 10,
    E_HQ_COLUMN_AMOUNT : 11,
    E_HQ_COLUMN_CURVOL : 12,
    E_HQ_COLUMN_CHANGE : 13,
    E_HQ_COLUMN_CHG : 14,
    E_HQ_COLUMN_AMPLITUDE : 15,
    E_HQ_COLUMN_AVGPRICE : 16,
    E_HQ_COLUMN_PREOPENINTEREST : 17,
    E_HQ_COLUMN_PRESETTLEMENTPRICE : 18,
    E_HQ_COLUMN_OPENINTEREST : 19,
    E_HQ_COLUMN_TURNOVERRATE : 20
};
Market.E_HQ_SORT_COLUMN._write = function(os, tag, val) { return os.writeInt32(tag, val); }
Market.E_HQ_SORT_COLUMN._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
Market.E_SORT_METHOD = {
    E_SORT_DEFAULT : 0,
    E_SORT_ASCEND : 1,
    E_SORT_DESCEN : 2
};
Market.E_SORT_METHOD._write = function(os, tag, val) { return os.writeInt32(tag, val); }
Market.E_SORT_METHOD._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }
Market.E_STOCK_HQ_DATA = {
    E_SHD_NONE : 0,
    E_SHD_SIMPLE : 1,
    E_SHD_EX : 2,
    E_SHD_ALL : 3
};
Market.E_STOCK_HQ_DATA._write = function(os, tag, val) { return os.writeInt32(tag, val); }
Market.E_STOCK_HQ_DATA._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }

Market.kLineData = function() {
    this.c = "";
    this.t = Market.HISTORY_DATA_TYPE.HDT_DAY_KLINE;
    this.o = "";
    this.n = "";
    this._classname = "Market.kLineData";
};
Market.kLineData.prototype = new TafStream.JceStruct();
Market.kLineData._classname = "Market.kLineData";

Market.kLineData._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.kLineData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.kLineData._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.kLineData();
    tmp.c = is.readString(0, true, "");
    tmp.t = is.readInt32(1, true, Market.HISTORY_DATA_TYPE.HDT_DAY_KLINE);
    tmp.o = is.readString(2, true, "");
    tmp.n = is.readString(3, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.kLineData.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.c);
    os.writeInt32(1, this.t);
    os.writeString(2, this.o);
    os.writeString(3, this.n);
    os.resumePrecision && os.resumePrecision();
};
Market.kLineData.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.kLineData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.kLineData.prototype.toObject = function() { 
    var tmp = {};

    tmp.c = this.c;
    tmp.t = this.t;
    tmp.o = this.o;
    tmp.n = this.n;
    
    return tmp;
}
Market.kLineData.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("c") || (this.c = json.c);
    !json.hasOwnProperty("t") || (this.t = json.t);
    !json.hasOwnProperty("o") || (this.o = json.o);
    !json.hasOwnProperty("n") || (this.n = json.n);
}
Market.kLineData.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.kLineData.new = function () {
    return new Market.kLineData();
}
Market.kLineData.create = function (is) {
    return Market.kLineData._readFrom(is);
}
Market.kLineDataReq = function() {
    this.vkLineData = new Market.kLineData();
    this._classname = "Market.kLineDataReq";
};
Market.kLineDataReq.prototype = new TafStream.JceStruct();
Market.kLineDataReq._classname = "Market.kLineDataReq";

Market.kLineDataReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.kLineDataReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.kLineDataReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.kLineDataReq();
    tmp.vkLineData = is.readStruct(0, true, Market.kLineData);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.kLineDataReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.vkLineData);
    os.resumePrecision && os.resumePrecision();
};
Market.kLineDataReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.kLineDataReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.kLineDataReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.vkLineData = this.vkLineData.toObject();
    
    return tmp;
}
Market.kLineDataReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vkLineData") || (this.vkLineData.readFromObject(json.vkLineData));
}
Market.kLineDataReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.kLineDataReq.new = function () {
    return new Market.kLineDataReq();
}
Market.kLineDataReq.create = function (is) {
    return Market.kLineDataReq._readFrom(is);
}
Market.kLineDataRsp = function() {
    this.rsp = "";
    this._classname = "Market.kLineDataRsp";
};
Market.kLineDataRsp.prototype = new TafStream.JceStruct();
Market.kLineDataRsp._classname = "Market.kLineDataRsp";

Market.kLineDataRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.kLineDataRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.kLineDataRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.kLineDataRsp();
    tmp.rsp = is.readString(0, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.kLineDataRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.rsp);
    os.resumePrecision && os.resumePrecision();
};
Market.kLineDataRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.kLineDataRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.kLineDataRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.rsp = this.rsp;
    
    return tmp;
}
Market.kLineDataRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("rsp") || (this.rsp = json.rsp);
}
Market.kLineDataRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.kLineDataRsp.new = function () {
    return new Market.kLineDataRsp();
}
Market.kLineDataRsp.create = function (is) {
    return Market.kLineDataRsp._readFrom(is);
}
Market.kLineInfoDataByPeriod = function() {
    this.c = "";
    this.s = "";
    this.e = "";
    this.n = "";
    this._classname = "Market.kLineInfoDataByPeriod";
};
Market.kLineInfoDataByPeriod.prototype = new TafStream.JceStruct();
Market.kLineInfoDataByPeriod._classname = "Market.kLineInfoDataByPeriod";

Market.kLineInfoDataByPeriod._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.kLineInfoDataByPeriod._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.kLineInfoDataByPeriod._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.kLineInfoDataByPeriod();
    tmp.c = is.readString(0, true, "");
    tmp.s = is.readString(1, true, "");
    tmp.e = is.readString(2, true, "");
    tmp.n = is.readString(3, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.kLineInfoDataByPeriod.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.c);
    os.writeString(1, this.s);
    os.writeString(2, this.e);
    os.writeString(3, this.n);
    os.resumePrecision && os.resumePrecision();
};
Market.kLineInfoDataByPeriod.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.kLineInfoDataByPeriod.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.kLineInfoDataByPeriod.prototype.toObject = function() { 
    var tmp = {};

    tmp.c = this.c;
    tmp.s = this.s;
    tmp.e = this.e;
    tmp.n = this.n;
    
    return tmp;
}
Market.kLineInfoDataByPeriod.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("c") || (this.c = json.c);
    !json.hasOwnProperty("s") || (this.s = json.s);
    !json.hasOwnProperty("e") || (this.e = json.e);
    !json.hasOwnProperty("n") || (this.n = json.n);
}
Market.kLineInfoDataByPeriod.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.kLineInfoDataByPeriod.new = function () {
    return new Market.kLineInfoDataByPeriod();
}
Market.kLineInfoDataByPeriod.create = function (is) {
    return Market.kLineInfoDataByPeriod._readFrom(is);
}
Market.kLineDataByPeriodReq = function() {
    this.vlist = new TafStream.List(Market.kLineInfoDataByPeriod);
    this._classname = "Market.kLineDataByPeriodReq";
};
Market.kLineDataByPeriodReq.prototype = new TafStream.JceStruct();
Market.kLineDataByPeriodReq._classname = "Market.kLineDataByPeriodReq";

Market.kLineDataByPeriodReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.kLineDataByPeriodReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.kLineDataByPeriodReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.kLineDataByPeriodReq();
    tmp.vlist = is.readList(0, true, TafStream.List(Market.kLineInfoDataByPeriod));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.kLineDataByPeriodReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeList(0, this.vlist);
    os.resumePrecision && os.resumePrecision();
};
Market.kLineDataByPeriodReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.kLineDataByPeriodReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.kLineDataByPeriodReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.vlist = this.vlist.toObject();
    
    return tmp;
}
Market.kLineDataByPeriodReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vlist") || (this.vlist.readFromObject(json.vlist));
}
Market.kLineDataByPeriodReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.kLineDataByPeriodReq.new = function () {
    return new Market.kLineDataByPeriodReq();
}
Market.kLineDataByPeriodReq.create = function (is) {
    return Market.kLineDataByPeriodReq._readFrom(is);
}
Market.kLineDataByPeriodRsp = function() {
    this.rsp = "";
    this._classname = "Market.kLineDataByPeriodRsp";
};
Market.kLineDataByPeriodRsp.prototype = new TafStream.JceStruct();
Market.kLineDataByPeriodRsp._classname = "Market.kLineDataByPeriodRsp";

Market.kLineDataByPeriodRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.kLineDataByPeriodRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.kLineDataByPeriodRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.kLineDataByPeriodRsp();
    tmp.rsp = is.readString(0, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.kLineDataByPeriodRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.rsp);
    os.resumePrecision && os.resumePrecision();
};
Market.kLineDataByPeriodRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.kLineDataByPeriodRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.kLineDataByPeriodRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.rsp = this.rsp;
    
    return tmp;
}
Market.kLineDataByPeriodRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("rsp") || (this.rsp = json.rsp);
}
Market.kLineDataByPeriodRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.kLineDataByPeriodRsp.new = function () {
    return new Market.kLineDataByPeriodRsp();
}
Market.kLineDataByPeriodRsp.create = function (is) {
    return Market.kLineDataByPeriodRsp._readFrom(is);
}
Market.stkCode = function() {
    this.c = "";
    this._classname = "Market.stkCode";
};
Market.stkCode.prototype = new TafStream.JceStruct();
Market.stkCode._classname = "Market.stkCode";

Market.stkCode._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.stkCode._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.stkCode._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.stkCode();
    tmp.c = is.readString(0, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.stkCode.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.c);
    os.resumePrecision && os.resumePrecision();
};
Market.stkCode.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.stkCode.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.stkCode.prototype.toObject = function() { 
    var tmp = {};

    tmp.c = this.c;
    
    return tmp;
}
Market.stkCode.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("c") || (this.c = json.c);
}
Market.stkCode.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.stkCode.new = function () {
    return new Market.stkCode();
}
Market.stkCode.create = function (is) {
    return Market.stkCode._readFrom(is);
}
Market.rtMinDataReq = function() {
    this.sCode = new Market.stkCode();
    this._classname = "Market.rtMinDataReq";
};
Market.rtMinDataReq.prototype = new TafStream.JceStruct();
Market.rtMinDataReq._classname = "Market.rtMinDataReq";

Market.rtMinDataReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.rtMinDataReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.rtMinDataReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.rtMinDataReq();
    tmp.sCode = is.readStruct(0, true, Market.stkCode);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.rtMinDataReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.sCode);
    os.resumePrecision && os.resumePrecision();
};
Market.rtMinDataReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.rtMinDataReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.rtMinDataReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.sCode = this.sCode.toObject();
    
    return tmp;
}
Market.rtMinDataReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("sCode") || (this.sCode.readFromObject(json.sCode));
}
Market.rtMinDataReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.rtMinDataReq.new = function () {
    return new Market.rtMinDataReq();
}
Market.rtMinDataReq.create = function (is) {
    return Market.rtMinDataReq._readFrom(is);
}
Market.rtMinDataRsp = function() {
    this.rsp = "";
    this._classname = "Market.rtMinDataRsp";
};
Market.rtMinDataRsp.prototype = new TafStream.JceStruct();
Market.rtMinDataRsp._classname = "Market.rtMinDataRsp";

Market.rtMinDataRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.rtMinDataRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.rtMinDataRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.rtMinDataRsp();
    tmp.rsp = is.readString(0, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.rtMinDataRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.rsp);
    os.resumePrecision && os.resumePrecision();
};
Market.rtMinDataRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.rtMinDataRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.rtMinDataRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.rsp = this.rsp;
    
    return tmp;
}
Market.rtMinDataRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("rsp") || (this.rsp = json.rsp);
}
Market.rtMinDataRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.rtMinDataRsp.new = function () {
    return new Market.rtMinDataRsp();
}
Market.rtMinDataRsp.create = function (is) {
    return Market.rtMinDataRsp._readFrom(is);
}
Market.type2StockSimpleReq = function() {
    this.type = Market.E_BUSS_TYPE.EBT_A;
    this.data = Market.E_STOCK_HQ_DATA.E_SHD_NONE;
    this.sortCol = Market.E_HQ_SORT_COLUMN.E_HQ_COLUMN_CODE;
    this.sore = Market.E_SORT_METHOD.E_SORT_DEFAULT;
    this._classname = "Market.type2StockSimpleReq";
};
Market.type2StockSimpleReq.prototype = new TafStream.JceStruct();
Market.type2StockSimpleReq._classname = "Market.type2StockSimpleReq";

Market.type2StockSimpleReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.type2StockSimpleReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.type2StockSimpleReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.type2StockSimpleReq();
    tmp.type = is.readInt32(0, true, Market.E_BUSS_TYPE.EBT_A);
    tmp.data = is.readInt32(1, true, Market.E_STOCK_HQ_DATA.E_SHD_NONE);
    tmp.sortCol = is.readInt32(2, true, Market.E_HQ_SORT_COLUMN.E_HQ_COLUMN_CODE);
    tmp.sore = is.readInt32(3, true, Market.E_SORT_METHOD.E_SORT_DEFAULT);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.type2StockSimpleReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.type);
    os.writeInt32(1, this.data);
    os.writeInt32(2, this.sortCol);
    os.writeInt32(3, this.sore);
    os.resumePrecision && os.resumePrecision();
};
Market.type2StockSimpleReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.type2StockSimpleReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.type2StockSimpleReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.type = this.type;
    tmp.data = this.data;
    tmp.sortCol = this.sortCol;
    tmp.sore = this.sore;
    
    return tmp;
}
Market.type2StockSimpleReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("type") || (this.type = json.type);
    !json.hasOwnProperty("data") || (this.data = json.data);
    !json.hasOwnProperty("sortCol") || (this.sortCol = json.sortCol);
    !json.hasOwnProperty("sore") || (this.sore = json.sore);
}
Market.type2StockSimpleReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.type2StockSimpleReq.new = function () {
    return new Market.type2StockSimpleReq();
}
Market.type2StockSimpleReq.create = function (is) {
    return Market.type2StockSimpleReq._readFrom(is);
}
Market.type2StockSimpleRsp = function() {
    this.rsp = "";
    this._classname = "Market.type2StockSimpleRsp";
};
Market.type2StockSimpleRsp.prototype = new TafStream.JceStruct();
Market.type2StockSimpleRsp._classname = "Market.type2StockSimpleRsp";

Market.type2StockSimpleRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.type2StockSimpleRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.type2StockSimpleRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.type2StockSimpleRsp();
    tmp.rsp = is.readString(0, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.type2StockSimpleRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.rsp);
    os.resumePrecision && os.resumePrecision();
};
Market.type2StockSimpleRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.type2StockSimpleRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.type2StockSimpleRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.rsp = this.rsp;
    
    return tmp;
}
Market.type2StockSimpleRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("rsp") || (this.rsp = json.rsp);
}
Market.type2StockSimpleRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.type2StockSimpleRsp.new = function () {
    return new Market.type2StockSimpleRsp();
}
Market.type2StockSimpleRsp.create = function (is) {
    return Market.type2StockSimpleRsp._readFrom(is);
}
Market.stockHqReq = function() {
    this.vlist = new TafStream.List(Market.stkCode);
    this._classname = "Market.stockHqReq";
};
Market.stockHqReq.prototype = new TafStream.JceStruct();
Market.stockHqReq._classname = "Market.stockHqReq";

Market.stockHqReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.stockHqReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.stockHqReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.stockHqReq();
    tmp.vlist = is.readList(0, true, TafStream.List(Market.stkCode));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.stockHqReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeList(0, this.vlist);
    os.resumePrecision && os.resumePrecision();
};
Market.stockHqReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.stockHqReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.stockHqReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.vlist = this.vlist.toObject();
    
    return tmp;
}
Market.stockHqReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("vlist") || (this.vlist.readFromObject(json.vlist));
}
Market.stockHqReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.stockHqReq.new = function () {
    return new Market.stockHqReq();
}
Market.stockHqReq.create = function (is) {
    return Market.stockHqReq._readFrom(is);
}
Market.stockHqRsp = function() {
    this.rsp = "";
    this._classname = "Market.stockHqRsp";
};
Market.stockHqRsp.prototype = new TafStream.JceStruct();
Market.stockHqRsp._classname = "Market.stockHqRsp";

Market.stockHqRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.stockHqRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.stockHqRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.stockHqRsp();
    tmp.rsp = is.readString(0, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.stockHqRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.rsp);
    os.resumePrecision && os.resumePrecision();
};
Market.stockHqRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.stockHqRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.stockHqRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.rsp = this.rsp;
    
    return tmp;
}
Market.stockHqRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("rsp") || (this.rsp = json.rsp);
}
Market.stockHqRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.stockHqRsp.new = function () {
    return new Market.stockHqRsp();
}
Market.stockHqRsp.create = function (is) {
    return Market.stockHqRsp._readFrom(is);
}
Market.tickDataReq = function() {
    this.sCode = new Market.stkCode();
    this._classname = "Market.tickDataReq";
};
Market.tickDataReq.prototype = new TafStream.JceStruct();
Market.tickDataReq._classname = "Market.tickDataReq";

Market.tickDataReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.tickDataReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.tickDataReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.tickDataReq();
    tmp.sCode = is.readStruct(0, true, Market.stkCode);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.tickDataReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeStruct(0, this.sCode);
    os.resumePrecision && os.resumePrecision();
};
Market.tickDataReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.tickDataReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.tickDataReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.sCode = this.sCode.toObject();
    
    return tmp;
}
Market.tickDataReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("sCode") || (this.sCode.readFromObject(json.sCode));
}
Market.tickDataReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.tickDataReq.new = function () {
    return new Market.tickDataReq();
}
Market.tickDataReq.create = function (is) {
    return Market.tickDataReq._readFrom(is);
}
Market.tickDataRsp = function() {
    this.rsp = "";
    this._classname = "Market.tickDataRsp";
};
Market.tickDataRsp.prototype = new TafStream.JceStruct();
Market.tickDataRsp._classname = "Market.tickDataRsp";

Market.tickDataRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
Market.tickDataRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
Market.tickDataRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new Market.tickDataRsp();
    tmp.rsp = is.readString(0, true, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
Market.tickDataRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.rsp);
    os.resumePrecision && os.resumePrecision();
};
Market.tickDataRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
Market.tickDataRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
Market.tickDataRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.rsp = this.rsp;
    
    return tmp;
}
Market.tickDataRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("rsp") || (this.rsp = json.rsp);
}
Market.tickDataRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
Market.tickDataRsp.new = function () {
    return new Market.tickDataRsp();
}
Market.tickDataRsp.create = function (is) {
    return Market.tickDataRsp._readFrom(is);
}

Market.WebHQProxy.prototype.kLineData = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, Market.kLineDataRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('kLineData', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

Market.WebHQProxy.prototype.kLineDataByPeriod = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, Market.kLineDataByPeriodRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('kLineDataByPeriod', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

Market.WebHQProxy.prototype.rtMinData = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, Market.rtMinDataRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('rtMinData', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

Market.WebHQProxy.prototype.stockHq = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, Market.stockHqRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('stockHq', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

Market.WebHQProxy.prototype.tickData = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, Market.tickDataRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('tickData', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

Market.WebHQProxy.prototype.type2StockSimple = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, Market.type2StockSimpleRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('type2StockSimple', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}



