// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 4.2.2 by TAF Team.
// Generated from `./NewsServer.jce'
// **********************************************************************

var TafStream = require('@taf/taf-stream');
var TafError  = require('@taf/taf-rpc').error;

if(TafStream.JceStruct == undefined){
TafStream.JceStruct = function() {
this._jce_double_precision_ = -1;
}
TafStream.JceStruct.prototype.setPrecision = function(d) {
if ((d == -1) || (d >= 0 && d <= 15)) {
this._jce_double_precision_ = d;
return true;
}
return false;
}
TafStream.JceStruct.prototype.resetPrecision = function() { this._jce_double_precision_ = -1;}
TafStream.JceStruct.prototype.hasSetPrecision = function() { return (this._jce_double_precision_ >= 0 && this._jce_double_precision_ <= 15);}
TafStream.JceStruct.prototype.getPrecision = function() { return this._jce_double_precision_; }
}

var News = News || {};
module.exports.News = News;

News.NewsInterfProxy = function () {
    this._name   = undefined;
    this._worker = undefined;
}

News.NewsInterfProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
}

News.NewsInterfProxy.prototype.getTimeout = function ( ) {
    return this._worker.timeout;
}


News.SUB_SORT_TYPE = {
    HOT_SUB : 1,
    EXCEP_SUB : 2,
    NEWS_SUB : 3,
    TOP_SUB : 4
};
News.SUB_SORT_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); }
News.SUB_SORT_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); }

News.MarketVane = function() {
    this.stockCode = "";
    this.market = 0;
    this.vane = 0;
    this.advise = "";
    this.upprob = 0;
    this.flucFlor = 0;
    this.flucCeil = 0;
    this.flucPrice = 0;
    this.fullPosition = 0;
    this.advisePosition = 0;
    this.price = 0;
    this.zd = 0;
    this.zdf = 0;
    this._classname = "News.MarketVane";
};
News.MarketVane.prototype = new TafStream.JceStruct();
News.MarketVane._classname = "News.MarketVane";

News.MarketVane._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.MarketVane._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.MarketVane._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.MarketVane();
    tmp.stockCode = is.readString(0, true, "");
    tmp.market = is.readInt32(1, true, 0);
    tmp.vane = is.readInt32(2, false, 0);
    tmp.advise = is.readString(3, false, "");
    tmp.upprob = is.readDouble(4, false, 0);
    tmp.flucFlor = is.readDouble(5, false, 0);
    tmp.flucCeil = is.readDouble(6, false, 0);
    tmp.flucPrice = is.readDouble(7, false, 0);
    tmp.fullPosition = is.readDouble(8, false, 0);
    tmp.advisePosition = is.readDouble(9, false, 0);
    tmp.price = is.readDouble(10, false, 0);
    tmp.zd = is.readDouble(11, false, 0);
    tmp.zdf = is.readDouble(12, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.MarketVane.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.stockCode);
    os.writeInt32(1, this.market);
    if (this.vane != undefined && this.vane != 0) {
        os.writeInt32(2, this.vane);
    }
    if (this.advise != undefined && this.advise != "") {
        os.writeString(3, this.advise);
    }
    if (this.upprob != undefined && this.upprob != 0) {
        os.writeDouble(4, this.upprob);
    }
    if (this.flucFlor != undefined && this.flucFlor != 0) {
        os.writeDouble(5, this.flucFlor);
    }
    if (this.flucCeil != undefined && this.flucCeil != 0) {
        os.writeDouble(6, this.flucCeil);
    }
    if (this.flucPrice != undefined && this.flucPrice != 0) {
        os.writeDouble(7, this.flucPrice);
    }
    if (this.fullPosition != undefined && this.fullPosition != 0) {
        os.writeDouble(8, this.fullPosition);
    }
    if (this.advisePosition != undefined && this.advisePosition != 0) {
        os.writeDouble(9, this.advisePosition);
    }
    if (this.price != undefined && this.price != 0) {
        os.writeDouble(10, this.price);
    }
    if (this.zd != undefined && this.zd != 0) {
        os.writeDouble(11, this.zd);
    }
    if (this.zdf != undefined && this.zdf != 0) {
        os.writeDouble(12, this.zdf);
    }
    os.resumePrecision && os.resumePrecision();
};
News.MarketVane.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.MarketVane.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.MarketVane.prototype.toObject = function() { 
    var tmp = {};

    tmp.stockCode = this.stockCode;
    tmp.market = this.market;
    tmp.vane = this.vane;
    tmp.advise = this.advise;
    tmp.upprob = this.upprob;
    tmp.flucFlor = this.flucFlor;
    tmp.flucCeil = this.flucCeil;
    tmp.flucPrice = this.flucPrice;
    tmp.fullPosition = this.fullPosition;
    tmp.advisePosition = this.advisePosition;
    tmp.price = this.price;
    tmp.zd = this.zd;
    tmp.zdf = this.zdf;
    
    return tmp;
}
News.MarketVane.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("stockCode") || (this.stockCode = json.stockCode);
    !json.hasOwnProperty("market") || (this.market = json.market);
    !json.hasOwnProperty("vane") || (this.vane = json.vane);
    !json.hasOwnProperty("advise") || (this.advise = json.advise);
    !json.hasOwnProperty("upprob") || (this.upprob = json.upprob);
    !json.hasOwnProperty("flucFlor") || (this.flucFlor = json.flucFlor);
    !json.hasOwnProperty("flucCeil") || (this.flucCeil = json.flucCeil);
    !json.hasOwnProperty("flucPrice") || (this.flucPrice = json.flucPrice);
    !json.hasOwnProperty("fullPosition") || (this.fullPosition = json.fullPosition);
    !json.hasOwnProperty("advisePosition") || (this.advisePosition = json.advisePosition);
    !json.hasOwnProperty("price") || (this.price = json.price);
    !json.hasOwnProperty("zd") || (this.zd = json.zd);
    !json.hasOwnProperty("zdf") || (this.zdf = json.zdf);
}
News.MarketVane.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.MarketVane.new = function () {
    return new News.MarketVane();
}
News.MarketVane.create = function (is) {
    return News.MarketVane._readFrom(is);
}
News.MarketVaneRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.marketVaneList = new TafStream.List(News.MarketVane);
    this._classname = "News.MarketVaneRsp";
};
News.MarketVaneRsp.prototype = new TafStream.JceStruct();
News.MarketVaneRsp._classname = "News.MarketVaneRsp";

News.MarketVaneRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.MarketVaneRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.MarketVaneRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.MarketVaneRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.marketVaneList = is.readList(2, false, TafStream.List(News.MarketVane));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.MarketVaneRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.marketVaneList != undefined && this.marketVaneList.length > 0) {
        os.writeList(2, this.marketVaneList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.MarketVaneRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.MarketVaneRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.MarketVaneRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.marketVaneList = this.marketVaneList.toObject();
    
    return tmp;
}
News.MarketVaneRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("marketVaneList") || (this.marketVaneList.readFromObject(json.marketVaneList));
}
News.MarketVaneRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.MarketVaneRsp.new = function () {
    return new News.MarketVaneRsp();
}
News.MarketVaneRsp.create = function (is) {
    return News.MarketVaneRsp._readFrom(is);
}
News.StockInfo = function() {
    this.stockCode = "";
    this.stockName = "";
    this.market = 0;
    this.price = 0;
    this.zdf = 0;
    this.zd = 0;
    this._classname = "News.StockInfo";
};
News.StockInfo.prototype = new TafStream.JceStruct();
News.StockInfo._classname = "News.StockInfo";

News.StockInfo._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.StockInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.StockInfo._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.StockInfo();
    tmp.stockCode = is.readString(0, true, "");
    tmp.stockName = is.readString(1, true, "");
    tmp.market = is.readInt32(2, true, 0);
    tmp.price = is.readDouble(3, false, 0);
    tmp.zdf = is.readDouble(4, false, 0);
    tmp.zd = is.readDouble(5, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.StockInfo.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.stockCode);
    os.writeString(1, this.stockName);
    os.writeInt32(2, this.market);
    if (this.price != undefined && this.price != 0) {
        os.writeDouble(3, this.price);
    }
    if (this.zdf != undefined && this.zdf != 0) {
        os.writeDouble(4, this.zdf);
    }
    if (this.zd != undefined && this.zd != 0) {
        os.writeDouble(5, this.zd);
    }
    os.resumePrecision && os.resumePrecision();
};
News.StockInfo.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.StockInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.StockInfo.prototype.toObject = function() { 
    var tmp = {};

    tmp.stockCode = this.stockCode;
    tmp.stockName = this.stockName;
    tmp.market = this.market;
    tmp.price = this.price;
    tmp.zdf = this.zdf;
    tmp.zd = this.zd;
    
    return tmp;
}
News.StockInfo.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("stockCode") || (this.stockCode = json.stockCode);
    !json.hasOwnProperty("stockName") || (this.stockName = json.stockName);
    !json.hasOwnProperty("market") || (this.market = json.market);
    !json.hasOwnProperty("price") || (this.price = json.price);
    !json.hasOwnProperty("zdf") || (this.zdf = json.zdf);
    !json.hasOwnProperty("zd") || (this.zd = json.zd);
}
News.StockInfo.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.StockInfo.new = function () {
    return new News.StockInfo();
}
News.StockInfo.create = function (is) {
    return News.StockInfo._readFrom(is);
}
News.SubJect = function() {
    this.code = "";
    this.name = "";
    this.newsId = "";
    this.title = "";
    this.rankDate = "";
    this.hot = 0;
    this.chgRatio = 0;
    this.type = 0;
    this.stockList = new TafStream.List(News.StockInfo);
    this._classname = "News.SubJect";
};
News.SubJect.prototype = new TafStream.JceStruct();
News.SubJect._classname = "News.SubJect";

News.SubJect._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.SubJect._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.SubJect._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.SubJect();
    tmp.code = is.readString(0, true, "");
    tmp.name = is.readString(1, true, "");
    tmp.newsId = is.readString(2, false, "");
    tmp.title = is.readString(3, false, "");
    tmp.rankDate = is.readString(4, false, "");
    tmp.hot = is.readDouble(5, false, 0);
    tmp.chgRatio = is.readDouble(6, false, 0);
    tmp.type = is.readInt32(7, false, 0);
    tmp.stockList = is.readList(8, false, TafStream.List(News.StockInfo));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.SubJect.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.code);
    os.writeString(1, this.name);
    if (this.newsId != undefined && this.newsId != "") {
        os.writeString(2, this.newsId);
    }
    if (this.title != undefined && this.title != "") {
        os.writeString(3, this.title);
    }
    if (this.rankDate != undefined && this.rankDate != "") {
        os.writeString(4, this.rankDate);
    }
    if (this.hot != undefined && this.hot != 0) {
        os.writeDouble(5, this.hot);
    }
    if (this.chgRatio != undefined && this.chgRatio != 0) {
        os.writeDouble(6, this.chgRatio);
    }
    if (this.type != undefined && this.type != 0) {
        os.writeInt32(7, this.type);
    }
    if (this.stockList != undefined && this.stockList.length > 0) {
        os.writeList(8, this.stockList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.SubJect.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.SubJect.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.SubJect.prototype.toObject = function() { 
    var tmp = {};

    tmp.code = this.code;
    tmp.name = this.name;
    tmp.newsId = this.newsId;
    tmp.title = this.title;
    tmp.rankDate = this.rankDate;
    tmp.hot = this.hot;
    tmp.chgRatio = this.chgRatio;
    tmp.type = this.type;
    tmp.stockList = this.stockList.toObject();
    
    return tmp;
}
News.SubJect.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("code") || (this.code = json.code);
    !json.hasOwnProperty("name") || (this.name = json.name);
    !json.hasOwnProperty("newsId") || (this.newsId = json.newsId);
    !json.hasOwnProperty("title") || (this.title = json.title);
    !json.hasOwnProperty("rankDate") || (this.rankDate = json.rankDate);
    !json.hasOwnProperty("hot") || (this.hot = json.hot);
    !json.hasOwnProperty("chgRatio") || (this.chgRatio = json.chgRatio);
    !json.hasOwnProperty("type") || (this.type = json.type);
    !json.hasOwnProperty("stockList") || (this.stockList.readFromObject(json.stockList));
}
News.SubJect.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.SubJect.new = function () {
    return new News.SubJect();
}
News.SubJect.create = function (is) {
    return News.SubJect._readFrom(is);
}
News.SubJectChartRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.dataJsonStr = "";
    this._classname = "News.SubJectChartRsp";
};
News.SubJectChartRsp.prototype = new TafStream.JceStruct();
News.SubJectChartRsp._classname = "News.SubJectChartRsp";

News.SubJectChartRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.SubJectChartRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.SubJectChartRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.SubJectChartRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.dataJsonStr = is.readString(2, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.SubJectChartRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.dataJsonStr != undefined && this.dataJsonStr != "") {
        os.writeString(2, this.dataJsonStr);
    }
    os.resumePrecision && os.resumePrecision();
};
News.SubJectChartRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.SubJectChartRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.SubJectChartRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.dataJsonStr = this.dataJsonStr;
    
    return tmp;
}
News.SubJectChartRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("dataJsonStr") || (this.dataJsonStr = json.dataJsonStr);
}
News.SubJectChartRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.SubJectChartRsp.new = function () {
    return new News.SubJectChartRsp();
}
News.SubJectChartRsp.create = function (is) {
    return News.SubJectChartRsp._readFrom(is);
}
News.SubJectsReq = function() {
    this.sortType = News.SUB_SORT_TYPE.HOT_SUB;
    this._classname = "News.SubJectsReq";
};
News.SubJectsReq.prototype = new TafStream.JceStruct();
News.SubJectsReq._classname = "News.SubJectsReq";

News.SubJectsReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.SubJectsReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.SubJectsReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.SubJectsReq();
    tmp.sortType = is.readInt32(0, true, News.SUB_SORT_TYPE.HOT_SUB);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.SubJectsReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.sortType);
    os.resumePrecision && os.resumePrecision();
};
News.SubJectsReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.SubJectsReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.SubJectsReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.sortType = this.sortType;
    
    return tmp;
}
News.SubJectsReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("sortType") || (this.sortType = json.sortType);
}
News.SubJectsReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.SubJectsReq.new = function () {
    return new News.SubJectsReq();
}
News.SubJectsReq.create = function (is) {
    return News.SubJectsReq._readFrom(is);
}
News.SubJectsRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.subJectList = new TafStream.List(News.SubJect);
    this._classname = "News.SubJectsRsp";
};
News.SubJectsRsp.prototype = new TafStream.JceStruct();
News.SubJectsRsp._classname = "News.SubJectsRsp";

News.SubJectsRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.SubJectsRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.SubJectsRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.SubJectsRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.subJectList = is.readList(2, false, TafStream.List(News.SubJect));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.SubJectsRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.subJectList != undefined && this.subJectList.length > 0) {
        os.writeList(2, this.subJectList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.SubJectsRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.SubJectsRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.SubJectsRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.subJectList = this.subJectList.toObject();
    
    return tmp;
}
News.SubJectsRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("subJectList") || (this.subJectList.readFromObject(json.subJectList));
}
News.SubJectsRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.SubJectsRsp.new = function () {
    return new News.SubJectsRsp();
}
News.SubJectsRsp.create = function (is) {
    return News.SubJectsRsp._readFrom(is);
}
News.RelatedTheme = function() {
    this.code = "";
    this.name = "";
    this.price = 0;
    this.zdf = 0;
    this._classname = "News.RelatedTheme";
};
News.RelatedTheme.prototype = new TafStream.JceStruct();
News.RelatedTheme._classname = "News.RelatedTheme";

News.RelatedTheme._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.RelatedTheme._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.RelatedTheme._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.RelatedTheme();
    tmp.code = is.readString(0, false, "");
    tmp.name = is.readString(1, false, "");
    tmp.price = is.readDouble(2, false, 0);
    tmp.zdf = is.readDouble(3, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.RelatedTheme.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.code != undefined && this.code != "") {
        os.writeString(0, this.code);
    }
    if (this.name != undefined && this.name != "") {
        os.writeString(1, this.name);
    }
    if (this.price != undefined && this.price != 0) {
        os.writeDouble(2, this.price);
    }
    if (this.zdf != undefined && this.zdf != 0) {
        os.writeDouble(3, this.zdf);
    }
    os.resumePrecision && os.resumePrecision();
};
News.RelatedTheme.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.RelatedTheme.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.RelatedTheme.prototype.toObject = function() { 
    var tmp = {};

    tmp.code = this.code;
    tmp.name = this.name;
    tmp.price = this.price;
    tmp.zdf = this.zdf;
    
    return tmp;
}
News.RelatedTheme.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("code") || (this.code = json.code);
    !json.hasOwnProperty("name") || (this.name = json.name);
    !json.hasOwnProperty("price") || (this.price = json.price);
    !json.hasOwnProperty("zdf") || (this.zdf = json.zdf);
}
News.RelatedTheme.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.RelatedTheme.new = function () {
    return new News.RelatedTheme();
}
News.RelatedTheme.create = function (is) {
    return News.RelatedTheme._readFrom(is);
}
News.RelatedStock = function() {
    this.code = "";
    this.name = "";
    this.market = 0;
    this.reason = "";
    this.price = 0;
    this.zdf = 0;
    this._classname = "News.RelatedStock";
};
News.RelatedStock.prototype = new TafStream.JceStruct();
News.RelatedStock._classname = "News.RelatedStock";

News.RelatedStock._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.RelatedStock._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.RelatedStock._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.RelatedStock();
    tmp.code = is.readString(0, false, "");
    tmp.name = is.readString(1, false, "");
    tmp.market = is.readInt32(2, false, 0);
    tmp.reason = is.readString(3, false, "");
    tmp.price = is.readDouble(4, false, 0);
    tmp.zdf = is.readDouble(5, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.RelatedStock.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.code != undefined && this.code != "") {
        os.writeString(0, this.code);
    }
    if (this.name != undefined && this.name != "") {
        os.writeString(1, this.name);
    }
    if (this.market != undefined && this.market != 0) {
        os.writeInt32(2, this.market);
    }
    if (this.reason != undefined && this.reason != "") {
        os.writeString(3, this.reason);
    }
    if (this.price != undefined && this.price != 0) {
        os.writeDouble(4, this.price);
    }
    if (this.zdf != undefined && this.zdf != 0) {
        os.writeDouble(5, this.zdf);
    }
    os.resumePrecision && os.resumePrecision();
};
News.RelatedStock.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.RelatedStock.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.RelatedStock.prototype.toObject = function() { 
    var tmp = {};

    tmp.code = this.code;
    tmp.name = this.name;
    tmp.market = this.market;
    tmp.reason = this.reason;
    tmp.price = this.price;
    tmp.zdf = this.zdf;
    
    return tmp;
}
News.RelatedStock.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("code") || (this.code = json.code);
    !json.hasOwnProperty("name") || (this.name = json.name);
    !json.hasOwnProperty("market") || (this.market = json.market);
    !json.hasOwnProperty("reason") || (this.reason = json.reason);
    !json.hasOwnProperty("price") || (this.price = json.price);
    !json.hasOwnProperty("zdf") || (this.zdf = json.zdf);
}
News.RelatedStock.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.RelatedStock.new = function () {
    return new News.RelatedStock();
}
News.RelatedStock.create = function (is) {
    return News.RelatedStock._readFrom(is);
}
News.LhbNews = function() {
    this.topicId = "";
    this.title = "";
    this.valueTrend = "";
    this.time = "";
    this.isBull = 0;
    this.themeList = new TafStream.List(News.RelatedTheme);
    this.stockList = new TafStream.List(News.RelatedStock);
    this.drzf = 0;
    this.frzf = 0;
    this.trzf = 0;
    this.tyrzf = 0;
    this.totalRate = 0;
    this.upNum = 0;
    this.downNum = 0;
    this._classname = "News.LhbNews";
};
News.LhbNews.prototype = new TafStream.JceStruct();
News.LhbNews._classname = "News.LhbNews";

News.LhbNews._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.LhbNews._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.LhbNews._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.LhbNews();
    tmp.topicId = is.readString(0, true, "");
    tmp.title = is.readString(1, false, "");
    tmp.valueTrend = is.readString(2, false, "");
    tmp.time = is.readString(3, false, "");
    tmp.isBull = is.readInt32(4, false, 0);
    tmp.themeList = is.readList(5, false, TafStream.List(News.RelatedTheme));
    tmp.stockList = is.readList(6, false, TafStream.List(News.RelatedStock));
    tmp.drzf = is.readDouble(7, false, 0);
    tmp.frzf = is.readDouble(8, false, 0);
    tmp.trzf = is.readDouble(9, false, 0);
    tmp.tyrzf = is.readDouble(10, false, 0);
    tmp.totalRate = is.readDouble(11, false, 0);
    tmp.upNum = is.readInt32(12, false, 0);
    tmp.downNum = is.readInt32(13, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.LhbNews.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeString(0, this.topicId);
    if (this.title != undefined && this.title != "") {
        os.writeString(1, this.title);
    }
    if (this.valueTrend != undefined && this.valueTrend != "") {
        os.writeString(2, this.valueTrend);
    }
    if (this.time != undefined && this.time != "") {
        os.writeString(3, this.time);
    }
    if (this.isBull != undefined && this.isBull != 0) {
        os.writeInt32(4, this.isBull);
    }
    if (this.themeList != undefined && this.themeList.length > 0) {
        os.writeList(5, this.themeList);
    }
    if (this.stockList != undefined && this.stockList.length > 0) {
        os.writeList(6, this.stockList);
    }
    if (this.drzf != undefined && this.drzf != 0) {
        os.writeDouble(7, this.drzf);
    }
    if (this.frzf != undefined && this.frzf != 0) {
        os.writeDouble(8, this.frzf);
    }
    if (this.trzf != undefined && this.trzf != 0) {
        os.writeDouble(9, this.trzf);
    }
    if (this.tyrzf != undefined && this.tyrzf != 0) {
        os.writeDouble(10, this.tyrzf);
    }
    if (this.totalRate != undefined && this.totalRate != 0) {
        os.writeDouble(11, this.totalRate);
    }
    if (this.upNum != undefined && this.upNum != 0) {
        os.writeInt32(12, this.upNum);
    }
    if (this.downNum != undefined && this.downNum != 0) {
        os.writeInt32(13, this.downNum);
    }
    os.resumePrecision && os.resumePrecision();
};
News.LhbNews.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.LhbNews.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.LhbNews.prototype.toObject = function() { 
    var tmp = {};

    tmp.topicId = this.topicId;
    tmp.title = this.title;
    tmp.valueTrend = this.valueTrend;
    tmp.time = this.time;
    tmp.isBull = this.isBull;
    tmp.themeList = this.themeList.toObject();
    tmp.stockList = this.stockList.toObject();
    tmp.drzf = this.drzf;
    tmp.frzf = this.frzf;
    tmp.trzf = this.trzf;
    tmp.tyrzf = this.tyrzf;
    tmp.totalRate = this.totalRate;
    tmp.upNum = this.upNum;
    tmp.downNum = this.downNum;
    
    return tmp;
}
News.LhbNews.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("topicId") || (this.topicId = json.topicId);
    !json.hasOwnProperty("title") || (this.title = json.title);
    !json.hasOwnProperty("valueTrend") || (this.valueTrend = json.valueTrend);
    !json.hasOwnProperty("time") || (this.time = json.time);
    !json.hasOwnProperty("isBull") || (this.isBull = json.isBull);
    !json.hasOwnProperty("themeList") || (this.themeList.readFromObject(json.themeList));
    !json.hasOwnProperty("stockList") || (this.stockList.readFromObject(json.stockList));
    !json.hasOwnProperty("drzf") || (this.drzf = json.drzf);
    !json.hasOwnProperty("frzf") || (this.frzf = json.frzf);
    !json.hasOwnProperty("trzf") || (this.trzf = json.trzf);
    !json.hasOwnProperty("tyrzf") || (this.tyrzf = json.tyrzf);
    !json.hasOwnProperty("totalRate") || (this.totalRate = json.totalRate);
    !json.hasOwnProperty("upNum") || (this.upNum = json.upNum);
    !json.hasOwnProperty("downNum") || (this.downNum = json.downNum);
}
News.LhbNews.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.LhbNews.new = function () {
    return new News.LhbNews();
}
News.LhbNews.create = function (is) {
    return News.LhbNews._readFrom(is);
}
News.LhbNewsReq = function() {
    this.type = 0;
    this._classname = "News.LhbNewsReq";
};
News.LhbNewsReq.prototype = new TafStream.JceStruct();
News.LhbNewsReq._classname = "News.LhbNewsReq";

News.LhbNewsReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.LhbNewsReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.LhbNewsReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.LhbNewsReq();
    tmp.type = is.readInt32(0, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.LhbNewsReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.type != undefined && this.type != 0) {
        os.writeInt32(0, this.type);
    }
    os.resumePrecision && os.resumePrecision();
};
News.LhbNewsReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.LhbNewsReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.LhbNewsReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.type = this.type;
    
    return tmp;
}
News.LhbNewsReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("type") || (this.type = json.type);
}
News.LhbNewsReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.LhbNewsReq.new = function () {
    return new News.LhbNewsReq();
}
News.LhbNewsReq.create = function (is) {
    return News.LhbNewsReq._readFrom(is);
}
News.LhbHistoryReq = function() {
    this.startDate = "";
    this.endDate = "";
    this.wantNum = 0;
    this.beginTime = "";
    this.lastNewsTime = "";
    this.offset = 0;
    this._classname = "News.LhbHistoryReq";
};
News.LhbHistoryReq.prototype = new TafStream.JceStruct();
News.LhbHistoryReq._classname = "News.LhbHistoryReq";

News.LhbHistoryReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.LhbHistoryReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.LhbHistoryReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.LhbHistoryReq();
    tmp.startDate = is.readString(0, false, "");
    tmp.endDate = is.readString(1, false, "");
    tmp.wantNum = is.readInt32(2, false, 0);
    tmp.beginTime = is.readString(3, false, "");
    tmp.lastNewsTime = is.readString(4, false, "");
    tmp.offset = is.readInt32(5, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.LhbHistoryReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.startDate != undefined && this.startDate != "") {
        os.writeString(0, this.startDate);
    }
    if (this.endDate != undefined && this.endDate != "") {
        os.writeString(1, this.endDate);
    }
    if (this.wantNum != undefined && this.wantNum != 0) {
        os.writeInt32(2, this.wantNum);
    }
    if (this.beginTime != undefined && this.beginTime != "") {
        os.writeString(3, this.beginTime);
    }
    if (this.lastNewsTime != undefined && this.lastNewsTime != "") {
        os.writeString(4, this.lastNewsTime);
    }
    if (this.offset != undefined && this.offset != 0) {
        os.writeInt32(5, this.offset);
    }
    os.resumePrecision && os.resumePrecision();
};
News.LhbHistoryReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.LhbHistoryReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.LhbHistoryReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.startDate = this.startDate;
    tmp.endDate = this.endDate;
    tmp.wantNum = this.wantNum;
    tmp.beginTime = this.beginTime;
    tmp.lastNewsTime = this.lastNewsTime;
    tmp.offset = this.offset;
    
    return tmp;
}
News.LhbHistoryReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("startDate") || (this.startDate = json.startDate);
    !json.hasOwnProperty("endDate") || (this.endDate = json.endDate);
    !json.hasOwnProperty("wantNum") || (this.wantNum = json.wantNum);
    !json.hasOwnProperty("beginTime") || (this.beginTime = json.beginTime);
    !json.hasOwnProperty("lastNewsTime") || (this.lastNewsTime = json.lastNewsTime);
    !json.hasOwnProperty("offset") || (this.offset = json.offset);
}
News.LhbHistoryReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.LhbHistoryReq.new = function () {
    return new News.LhbHistoryReq();
}
News.LhbHistoryReq.create = function (is) {
    return News.LhbHistoryReq._readFrom(is);
}
News.LhbNewsRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.tradeStatus = "";
    this.lhbNewsList = new TafStream.List(News.LhbNews);
    this._classname = "News.LhbNewsRsp";
};
News.LhbNewsRsp.prototype = new TafStream.JceStruct();
News.LhbNewsRsp._classname = "News.LhbNewsRsp";

News.LhbNewsRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.LhbNewsRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.LhbNewsRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.LhbNewsRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.tradeStatus = is.readString(2, false, "");
    tmp.lhbNewsList = is.readList(3, false, TafStream.List(News.LhbNews));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.LhbNewsRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.tradeStatus != undefined && this.tradeStatus != "") {
        os.writeString(2, this.tradeStatus);
    }
    if (this.lhbNewsList != undefined && this.lhbNewsList.length > 0) {
        os.writeList(3, this.lhbNewsList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.LhbNewsRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.LhbNewsRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.LhbNewsRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.tradeStatus = this.tradeStatus;
    tmp.lhbNewsList = this.lhbNewsList.toObject();
    
    return tmp;
}
News.LhbNewsRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("tradeStatus") || (this.tradeStatus = json.tradeStatus);
    !json.hasOwnProperty("lhbNewsList") || (this.lhbNewsList.readFromObject(json.lhbNewsList));
}
News.LhbNewsRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.LhbNewsRsp.new = function () {
    return new News.LhbNewsRsp();
}
News.LhbNewsRsp.create = function (is) {
    return News.LhbNewsRsp._readFrom(is);
}
News.TopLhbNewsRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.tradeStatus = "";
    this.lhbNewsListLD = new TafStream.List(News.LhbNews);
    this.lhbNewsListLK = new TafStream.List(News.LhbNews);
    this._classname = "News.TopLhbNewsRsp";
};
News.TopLhbNewsRsp.prototype = new TafStream.JceStruct();
News.TopLhbNewsRsp._classname = "News.TopLhbNewsRsp";

News.TopLhbNewsRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.TopLhbNewsRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.TopLhbNewsRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.TopLhbNewsRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.tradeStatus = is.readString(2, false, "");
    tmp.lhbNewsListLD = is.readList(3, false, TafStream.List(News.LhbNews));
    tmp.lhbNewsListLK = is.readList(4, false, TafStream.List(News.LhbNews));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.TopLhbNewsRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.tradeStatus != undefined && this.tradeStatus != "") {
        os.writeString(2, this.tradeStatus);
    }
    if (this.lhbNewsListLD != undefined && this.lhbNewsListLD.length > 0) {
        os.writeList(3, this.lhbNewsListLD);
    }
    if (this.lhbNewsListLK != undefined && this.lhbNewsListLK.length > 0) {
        os.writeList(4, this.lhbNewsListLK);
    }
    os.resumePrecision && os.resumePrecision();
};
News.TopLhbNewsRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.TopLhbNewsRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.TopLhbNewsRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.tradeStatus = this.tradeStatus;
    tmp.lhbNewsListLD = this.lhbNewsListLD.toObject();
    tmp.lhbNewsListLK = this.lhbNewsListLK.toObject();
    
    return tmp;
}
News.TopLhbNewsRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("tradeStatus") || (this.tradeStatus = json.tradeStatus);
    !json.hasOwnProperty("lhbNewsListLD") || (this.lhbNewsListLD.readFromObject(json.lhbNewsListLD));
    !json.hasOwnProperty("lhbNewsListLK") || (this.lhbNewsListLK.readFromObject(json.lhbNewsListLK));
}
News.TopLhbNewsRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.TopLhbNewsRsp.new = function () {
    return new News.TopLhbNewsRsp();
}
News.TopLhbNewsRsp.create = function (is) {
    return News.TopLhbNewsRsp._readFrom(is);
}
News.LhbHistorysRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.tradeStatus = "";
    this.lhbNewsList = new TafStream.List(News.LhbNews);
    this.hasNext = 0;
    this.beginTime = "";
    this.total = 0;
    this._classname = "News.LhbHistorysRsp";
};
News.LhbHistorysRsp.prototype = new TafStream.JceStruct();
News.LhbHistorysRsp._classname = "News.LhbHistorysRsp";

News.LhbHistorysRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.LhbHistorysRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.LhbHistorysRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.LhbHistorysRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.tradeStatus = is.readString(2, false, "");
    tmp.lhbNewsList = is.readList(3, false, TafStream.List(News.LhbNews));
    tmp.hasNext = is.readInt32(4, false, 0);
    tmp.beginTime = is.readString(5, false, "");
    tmp.total = is.readInt32(6, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.LhbHistorysRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.tradeStatus != undefined && this.tradeStatus != "") {
        os.writeString(2, this.tradeStatus);
    }
    if (this.lhbNewsList != undefined && this.lhbNewsList.length > 0) {
        os.writeList(3, this.lhbNewsList);
    }
    if (this.hasNext != undefined && this.hasNext != 0) {
        os.writeInt32(4, this.hasNext);
    }
    if (this.beginTime != undefined && this.beginTime != "") {
        os.writeString(5, this.beginTime);
    }
    if (this.total != undefined && this.total != 0) {
        os.writeInt32(6, this.total);
    }
    os.resumePrecision && os.resumePrecision();
};
News.LhbHistorysRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.LhbHistorysRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.LhbHistorysRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.tradeStatus = this.tradeStatus;
    tmp.lhbNewsList = this.lhbNewsList.toObject();
    tmp.hasNext = this.hasNext;
    tmp.beginTime = this.beginTime;
    tmp.total = this.total;
    
    return tmp;
}
News.LhbHistorysRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("tradeStatus") || (this.tradeStatus = json.tradeStatus);
    !json.hasOwnProperty("lhbNewsList") || (this.lhbNewsList.readFromObject(json.lhbNewsList));
    !json.hasOwnProperty("hasNext") || (this.hasNext = json.hasNext);
    !json.hasOwnProperty("beginTime") || (this.beginTime = json.beginTime);
    !json.hasOwnProperty("total") || (this.total = json.total);
}
News.LhbHistorysRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.LhbHistorysRsp.new = function () {
    return new News.LhbHistorysRsp();
}
News.LhbHistorysRsp.create = function (is) {
    return News.LhbHistorysRsp._readFrom(is);
}
News.HotChart = function() {
    this.code = "";
    this.date = "";
    this.hot = 0;
    this._classname = "News.HotChart";
};
News.HotChart.prototype = new TafStream.JceStruct();
News.HotChart._classname = "News.HotChart";

News.HotChart._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.HotChart._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.HotChart._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.HotChart();
    tmp.code = is.readString(0, false, "");
    tmp.date = is.readString(1, false, "");
    tmp.hot = is.readDouble(2, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.HotChart.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.code != undefined && this.code != "") {
        os.writeString(0, this.code);
    }
    if (this.date != undefined && this.date != "") {
        os.writeString(1, this.date);
    }
    if (this.hot != undefined && this.hot != 0) {
        os.writeDouble(2, this.hot);
    }
    os.resumePrecision && os.resumePrecision();
};
News.HotChart.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.HotChart.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.HotChart.prototype.toObject = function() { 
    var tmp = {};

    tmp.code = this.code;
    tmp.date = this.date;
    tmp.hot = this.hot;
    
    return tmp;
}
News.HotChart.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("code") || (this.code = json.code);
    !json.hasOwnProperty("date") || (this.date = json.date);
    !json.hasOwnProperty("hot") || (this.hot = json.hot);
}
News.HotChart.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.HotChart.new = function () {
    return new News.HotChart();
}
News.HotChart.create = function (is) {
    return News.HotChart._readFrom(is);
}
News.HotDayStock = function() {
    this.code = "";
    this.name = "";
    this.market = 0;
    this.price = 0;
    this.zdf = 0;
    this.hot = 0;
    this.chgRatio = 0;
    this.themeList = new TafStream.List(News.RelatedTheme);
    this.hotChartList = new TafStream.List(News.HotChart);
    this._classname = "News.HotDayStock";
};
News.HotDayStock.prototype = new TafStream.JceStruct();
News.HotDayStock._classname = "News.HotDayStock";

News.HotDayStock._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.HotDayStock._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.HotDayStock._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.HotDayStock();
    tmp.code = is.readString(0, false, "");
    tmp.name = is.readString(1, false, "");
    tmp.market = is.readInt32(2, false, 0);
    tmp.price = is.readDouble(3, false, 0);
    tmp.zdf = is.readDouble(4, false, 0);
    tmp.hot = is.readDouble(5, false, 0);
    tmp.chgRatio = is.readDouble(6, false, 0);
    tmp.themeList = is.readList(7, false, TafStream.List(News.RelatedTheme));
    tmp.hotChartList = is.readList(8, false, TafStream.List(News.HotChart));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.HotDayStock.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.code != undefined && this.code != "") {
        os.writeString(0, this.code);
    }
    if (this.name != undefined && this.name != "") {
        os.writeString(1, this.name);
    }
    if (this.market != undefined && this.market != 0) {
        os.writeInt32(2, this.market);
    }
    if (this.price != undefined && this.price != 0) {
        os.writeDouble(3, this.price);
    }
    if (this.zdf != undefined && this.zdf != 0) {
        os.writeDouble(4, this.zdf);
    }
    if (this.hot != undefined && this.hot != 0) {
        os.writeDouble(5, this.hot);
    }
    if (this.chgRatio != undefined && this.chgRatio != 0) {
        os.writeDouble(6, this.chgRatio);
    }
    if (this.themeList != undefined && this.themeList.length > 0) {
        os.writeList(7, this.themeList);
    }
    if (this.hotChartList != undefined && this.hotChartList.length > 0) {
        os.writeList(8, this.hotChartList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.HotDayStock.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.HotDayStock.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.HotDayStock.prototype.toObject = function() { 
    var tmp = {};

    tmp.code = this.code;
    tmp.name = this.name;
    tmp.market = this.market;
    tmp.price = this.price;
    tmp.zdf = this.zdf;
    tmp.hot = this.hot;
    tmp.chgRatio = this.chgRatio;
    tmp.themeList = this.themeList.toObject();
    tmp.hotChartList = this.hotChartList.toObject();
    
    return tmp;
}
News.HotDayStock.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("code") || (this.code = json.code);
    !json.hasOwnProperty("name") || (this.name = json.name);
    !json.hasOwnProperty("market") || (this.market = json.market);
    !json.hasOwnProperty("price") || (this.price = json.price);
    !json.hasOwnProperty("zdf") || (this.zdf = json.zdf);
    !json.hasOwnProperty("hot") || (this.hot = json.hot);
    !json.hasOwnProperty("chgRatio") || (this.chgRatio = json.chgRatio);
    !json.hasOwnProperty("themeList") || (this.themeList.readFromObject(json.themeList));
    !json.hasOwnProperty("hotChartList") || (this.hotChartList.readFromObject(json.hotChartList));
}
News.HotDayStock.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.HotDayStock.new = function () {
    return new News.HotDayStock();
}
News.HotDayStock.create = function (is) {
    return News.HotDayStock._readFrom(is);
}
News.HotDayStockRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.hotDayList = new TafStream.List(News.HotDayStock);
    this._classname = "News.HotDayStockRsp";
};
News.HotDayStockRsp.prototype = new TafStream.JceStruct();
News.HotDayStockRsp._classname = "News.HotDayStockRsp";

News.HotDayStockRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.HotDayStockRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.HotDayStockRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.HotDayStockRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.hotDayList = is.readList(2, false, TafStream.List(News.HotDayStock));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.HotDayStockRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.hotDayList != undefined && this.hotDayList.length > 0) {
        os.writeList(2, this.hotDayList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.HotDayStockRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.HotDayStockRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.HotDayStockRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.hotDayList = this.hotDayList.toObject();
    
    return tmp;
}
News.HotDayStockRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("hotDayList") || (this.hotDayList.readFromObject(json.hotDayList));
}
News.HotDayStockRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.HotDayStockRsp.new = function () {
    return new News.HotDayStockRsp();
}
News.HotDayStockRsp.create = function (is) {
    return News.HotDayStockRsp._readFrom(is);
}
News.HotWeekStock = function() {
    this.code = "";
    this.name = "";
    this.market = 0;
    this.price = 0;
    this.zdf = 0;
    this.themeList = new TafStream.List(News.RelatedTheme);
    this.weekProfit = 0;
    this._classname = "News.HotWeekStock";
};
News.HotWeekStock.prototype = new TafStream.JceStruct();
News.HotWeekStock._classname = "News.HotWeekStock";

News.HotWeekStock._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.HotWeekStock._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.HotWeekStock._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.HotWeekStock();
    tmp.code = is.readString(0, false, "");
    tmp.name = is.readString(1, false, "");
    tmp.market = is.readInt32(2, false, 0);
    tmp.price = is.readDouble(3, false, 0);
    tmp.zdf = is.readDouble(4, false, 0);
    tmp.themeList = is.readList(5, false, TafStream.List(News.RelatedTheme));
    tmp.weekProfit = is.readDouble(6, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.HotWeekStock.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.code != undefined && this.code != "") {
        os.writeString(0, this.code);
    }
    if (this.name != undefined && this.name != "") {
        os.writeString(1, this.name);
    }
    if (this.market != undefined && this.market != 0) {
        os.writeInt32(2, this.market);
    }
    if (this.price != undefined && this.price != 0) {
        os.writeDouble(3, this.price);
    }
    if (this.zdf != undefined && this.zdf != 0) {
        os.writeDouble(4, this.zdf);
    }
    if (this.themeList != undefined && this.themeList.length > 0) {
        os.writeList(5, this.themeList);
    }
    if (this.weekProfit != undefined && this.weekProfit != 0) {
        os.writeDouble(6, this.weekProfit);
    }
    os.resumePrecision && os.resumePrecision();
};
News.HotWeekStock.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.HotWeekStock.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.HotWeekStock.prototype.toObject = function() { 
    var tmp = {};

    tmp.code = this.code;
    tmp.name = this.name;
    tmp.market = this.market;
    tmp.price = this.price;
    tmp.zdf = this.zdf;
    tmp.themeList = this.themeList.toObject();
    tmp.weekProfit = this.weekProfit;
    
    return tmp;
}
News.HotWeekStock.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("code") || (this.code = json.code);
    !json.hasOwnProperty("name") || (this.name = json.name);
    !json.hasOwnProperty("market") || (this.market = json.market);
    !json.hasOwnProperty("price") || (this.price = json.price);
    !json.hasOwnProperty("zdf") || (this.zdf = json.zdf);
    !json.hasOwnProperty("themeList") || (this.themeList.readFromObject(json.themeList));
    !json.hasOwnProperty("weekProfit") || (this.weekProfit = json.weekProfit);
}
News.HotWeekStock.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.HotWeekStock.new = function () {
    return new News.HotWeekStock();
}
News.HotWeekStock.create = function (is) {
    return News.HotWeekStock._readFrom(is);
}
News.HotWeekStockRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.hotWeekList = new TafStream.List(News.HotWeekStock);
    this._classname = "News.HotWeekStockRsp";
};
News.HotWeekStockRsp.prototype = new TafStream.JceStruct();
News.HotWeekStockRsp._classname = "News.HotWeekStockRsp";

News.HotWeekStockRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.HotWeekStockRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.HotWeekStockRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.HotWeekStockRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.hotWeekList = is.readList(2, false, TafStream.List(News.HotWeekStock));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.HotWeekStockRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.hotWeekList != undefined && this.hotWeekList.length > 0) {
        os.writeList(2, this.hotWeekList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.HotWeekStockRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.HotWeekStockRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.HotWeekStockRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.hotWeekList = this.hotWeekList.toObject();
    
    return tmp;
}
News.HotWeekStockRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("hotWeekList") || (this.hotWeekList.readFromObject(json.hotWeekList));
}
News.HotWeekStockRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.HotWeekStockRsp.new = function () {
    return new News.HotWeekStockRsp();
}
News.HotWeekStockRsp.create = function (is) {
    return News.HotWeekStockRsp._readFrom(is);
}
News.WeekHistory = function() {
    this.date = "";
    this.weekProfit = 0;
    this.hsProfit = 0;
    this.stockList = new TafStream.List(News.HotWeekStock);
    this._classname = "News.WeekHistory";
};
News.WeekHistory.prototype = new TafStream.JceStruct();
News.WeekHistory._classname = "News.WeekHistory";

News.WeekHistory._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.WeekHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.WeekHistory._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.WeekHistory();
    tmp.date = is.readString(0, false, "");
    tmp.weekProfit = is.readDouble(1, false, 0);
    tmp.hsProfit = is.readDouble(2, false, 0);
    tmp.stockList = is.readList(3, false, TafStream.List(News.HotWeekStock));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.WeekHistory.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.date != undefined && this.date != "") {
        os.writeString(0, this.date);
    }
    if (this.weekProfit != undefined && this.weekProfit != 0) {
        os.writeDouble(1, this.weekProfit);
    }
    if (this.hsProfit != undefined && this.hsProfit != 0) {
        os.writeDouble(2, this.hsProfit);
    }
    if (this.stockList != undefined && this.stockList.length > 0) {
        os.writeList(3, this.stockList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.WeekHistory.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.WeekHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.WeekHistory.prototype.toObject = function() { 
    var tmp = {};

    tmp.date = this.date;
    tmp.weekProfit = this.weekProfit;
    tmp.hsProfit = this.hsProfit;
    tmp.stockList = this.stockList.toObject();
    
    return tmp;
}
News.WeekHistory.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("date") || (this.date = json.date);
    !json.hasOwnProperty("weekProfit") || (this.weekProfit = json.weekProfit);
    !json.hasOwnProperty("hsProfit") || (this.hsProfit = json.hsProfit);
    !json.hasOwnProperty("stockList") || (this.stockList.readFromObject(json.stockList));
}
News.WeekHistory.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.WeekHistory.new = function () {
    return new News.WeekHistory();
}
News.WeekHistory.create = function (is) {
    return News.WeekHistory._readFrom(is);
}
News.WeekHistoryReq = function() {
    this.startNum = 0;
    this.wantNum = 0;
    this._classname = "News.WeekHistoryReq";
};
News.WeekHistoryReq.prototype = new TafStream.JceStruct();
News.WeekHistoryReq._classname = "News.WeekHistoryReq";

News.WeekHistoryReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.WeekHistoryReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.WeekHistoryReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.WeekHistoryReq();
    tmp.startNum = is.readInt32(0, false, 0);
    tmp.wantNum = is.readInt32(1, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.WeekHistoryReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.startNum != undefined && this.startNum != 0) {
        os.writeInt32(0, this.startNum);
    }
    if (this.wantNum != undefined && this.wantNum != 0) {
        os.writeInt32(1, this.wantNum);
    }
    os.resumePrecision && os.resumePrecision();
};
News.WeekHistoryReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.WeekHistoryReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.WeekHistoryReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.startNum = this.startNum;
    tmp.wantNum = this.wantNum;
    
    return tmp;
}
News.WeekHistoryReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("startNum") || (this.startNum = json.startNum);
    !json.hasOwnProperty("wantNum") || (this.wantNum = json.wantNum);
}
News.WeekHistoryReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.WeekHistoryReq.new = function () {
    return new News.WeekHistoryReq();
}
News.WeekHistoryReq.create = function (is) {
    return News.WeekHistoryReq._readFrom(is);
}
News.WeekHistoryRsp = function() {
    this.iRet = 0;
    this.iMsg = "";
    this.weekHistoryList = new TafStream.List(News.WeekHistory);
    this._classname = "News.WeekHistoryRsp";
};
News.WeekHistoryRsp.prototype = new TafStream.JceStruct();
News.WeekHistoryRsp._classname = "News.WeekHistoryRsp";

News.WeekHistoryRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
News.WeekHistoryRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
News.WeekHistoryRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new News.WeekHistoryRsp();
    tmp.iRet = is.readInt32(0, true, 0);
    tmp.iMsg = is.readString(1, false, "");
    tmp.weekHistoryList = is.readList(2, false, TafStream.List(News.WeekHistory));
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
News.WeekHistoryRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    os.writeInt32(0, this.iRet);
    if (this.iMsg != undefined && this.iMsg != "") {
        os.writeString(1, this.iMsg);
    }
    if (this.weekHistoryList != undefined && this.weekHistoryList.length > 0) {
        os.writeList(2, this.weekHistoryList);
    }
    os.resumePrecision && os.resumePrecision();
};
News.WeekHistoryRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
News.WeekHistoryRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
News.WeekHistoryRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.iMsg = this.iMsg;
    tmp.weekHistoryList = this.weekHistoryList.toObject();
    
    return tmp;
}
News.WeekHistoryRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("iMsg") || (this.iMsg = json.iMsg);
    !json.hasOwnProperty("weekHistoryList") || (this.weekHistoryList.readFromObject(json.weekHistoryList));
}
News.WeekHistoryRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
News.WeekHistoryRsp.new = function () {
    return new News.WeekHistoryRsp();
}
News.WeekHistoryRsp.create = function (is) {
    return News.WeekHistoryRsp._readFrom(is);
}

News.NewsInterfProxy.prototype.getHotDayStock = function () {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(1, true, News.HotDayStockRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getHotDayStock', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

News.NewsInterfProxy.prototype.getHotWeekStock = function () {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(1, true, News.HotWeekStockRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getHotWeekStock', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

News.NewsInterfProxy.prototype.getLhbHistory = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, News.LhbHistorysRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getLhbHistory', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

News.NewsInterfProxy.prototype.getLhbNews = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, News.LhbNewsRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getLhbNews', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

News.NewsInterfProxy.prototype.getMarketVane = function () {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.marketVaneRsp = is.readStruct(1, true, News.MarketVaneRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getMarketVane', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

News.NewsInterfProxy.prototype.getSubJects = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, News.SubJectsRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getSubJects', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

News.NewsInterfProxy.prototype.getSubJectsChart = function () {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(1, true, News.SubJectChartRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getSubJectsChart', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

News.NewsInterfProxy.prototype.getTopLhbNews = function () {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(1, true, News.TopLhbNewsRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getTopLhbNews', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

News.NewsInterfProxy.prototype.getWeekHistoryStock = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, News.WeekHistoryRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('getWeekHistoryStock', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}



